### ISSUE TITLE
unpack API method returns "unsupported message type" error

### ISSUE THREAD

**Issue by deweller** [CounterpartyXCP/counterparty-lib#1018]
Calling unpack for a data hex returns an unsupported message type error.

Example transaction with an error

```
0100000001d3d1359af02917145a18e69c1373ca651ec314440dc30ac9024e9b08acdfd4b6000000006b483045022100f0bb37d394eeab4d62cd7c2e98704abe071f3b80f9fa2c831d4613af142d9343022047c6cb2c472716abc5e109ef1c6e09e1c9efff742b54e88a7aea5c75098b112b012103fe3a115e5c9641b1a9bdbe90221b4c9622ee83c9d0082bd2b7f81526ca1ca9a9ffffffff020000000000000000306a2e894e8cad5ea7a26d44d7ac8f779e575bbc1e2801c525f3772e094954e4174348fe8efe75fce3808d41e29f014cacf8a70400000000001976a91469e12a40d4a2218d33f208b9a0447894dc9bea3188ac00000000
```

**Comment by longhoangwkm** [comment]
#1026

**Comment by longhoangwkm** [comment]
@deweller Very appreciated if you can take a time for the above bug, many thanks

**Comment by chiguireitor** [comment]
Devon isn't currently working with the project, i'll take a look soon to it again, it seems the unpack isn't being routed through the correct message specific modules

**Comment by longhoangwkm** [comment]
@chiguireitor i wonder why counterparty wallet UI are still working as well  meanwhile this lib have error. It look like the current counterparty-lib which was using by Counterparty and this `counterparty-lib` are different versions.

Btw, i was getting stuck  in a month for Counterparty transaction, Very appreciated  if you can help, many thanks

**Comment by SFzxc** [comment]
:(
