### ISSUE TITLE
[Feature Request] Protocol-Level Address Sweep

### ISSUE THREAD

**Issue by livinginformation** [CounterpartyXCP/counterparty-lib#1020]
Currently, sweeping all assets from one address to another address requires sending each asset as an individual transaction. Soon (with MPMA sends), we can sweep with more efficiency, but will still require 8 bytes per asset. I would like to request the addition of the ability to sweep the entire contents of one address into another, at the protocol level (no need to enumerate the individual assets, just send every single one).

**Comment by deweller** [comment]
The next steps toward implementing this are to open a thread on https://counterpartytalk.org/ with an outline for a CIP proposal.

https://github.com/CounterpartyXCP/cips/blob/master/cip-0001.md

**Comment by chiguireitor** [comment]
DoneDone with CIP 20 https://github.com/CounterpartyXCP/cips/blob/cip20/cip-0020.md
