### ISSUE TITLE
create_btcpay error - 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1027]
There appears to be an issue with the `create_btcpay` API. The following error is thrown when trying to create a btcpay transaction during a valid/pending order match.

```'NoneType' object has no attribute 'split'```

The screenshots below show testnet transactions.

**`create_btcpay` request during valid order match... fails**
![image](https://user-images.githubusercontent.com/376028/35999799-d461964e-0cd5-11e8-8b0e-2b676cd315c4.png)

**`get_order_matches` request showing order match in 'pending' status**
![image](https://user-images.githubusercontent.com/376028/35999808-db487d74-0cd5-11e8-87a4-24f6aed59661.png)

**Comment by blockstrange** [comment]
👍 Hitting this as well:

<img width="1277" alt="screen shot 2018-02-25 at 16 28 04" src="https://user-images.githubusercontent.com/36556725/36703205-8aef0422-1b28-11e8-9a4f-b3b73fce1d12.png">

Mentioned it briefly in RPBT Telegram a bit ago. It appears to cause a new *Server error* dialog to appear for each error thrown. Thanks for the great wallet!

**Comment by jdogresorg** [comment]
After some further investigation, it appears that the `create_btcpay` transaction requires that a `source` address be specified, even though the documentation indicates `order_match_id` is the only required field.

We need to update the documentation at https://counterparty.io/docs/api/#create_btcpay to reflect that `source` is a required field
