### ISSUE TITLE
Child Asset Unauthorized to Lock without Parent

### ISSUE THREAD

**Issue by speaktech** [CounterpartyXCP/counterparty-lib#1053]
https://github.com/CounterpartyXCP/counterparty-lib/blob/e875c45c586cc4fc840a59540a6d44bd03ee698b/counterpartylib/lib/messages/issuance.py#L153-L163

I created an asset MATTIAC and then the child asset MATTIAC.AFXNYC
The parent asset ownership was sent to the artist and the child asset ownership was kept. Still being listed as the owner, I am attempting to lock the child asset without success. Freewallet is giving me the following: 

> Error composing issuance transaction via API: ['parent asset owned by another address']

After consulting J-Dog he instructed me that it is a protocol problem and that if replicable it is indeed an issue.

**Comment by chiguireitor** [comment]
Indeed sounds like a problem, marking as possible bug

**Comment by speaktech** [comment]
The three other functions are unavailable. Attempts to return the asset ownership, issue more tokens, or update the description all end in error. IMHO a fix should be sought after as this is in effect disabling a subasset once sent to another address without the parent token.

**Comment by jdogresorg** [comment]
All functionality is tied up in a single cp action called an issuance, and will all be fixed at the same time

**Comment by jdogresorg** [comment]
after some further testing... the issuance works if you specify the numeric asset name as "asset" instead of the "asset_longname" value as "asset"..... tho most people will probably want to specify the full asset name as "asset" and not use the numeric... so this issue still needs fixing :)

**Comment by jdogresorg** [comment]
fixed with commit 27f5b57

**Comment by jdogresorg** [comment]
@speaktech Please try locking your asset now and report back if you have any issues. 👍
