### ISSUE TITLE
create_dispenser - add subasset support

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1068]
The API documentation for `create_dispenser` indicates that the `asset` param can be an asset or subasset, however specifying a subasset name is not working and results in an error.

![image](https://user-images.githubusercontent.com/376028/74897958-60369b00-534d-11ea-9c18-0de27885abb0.png)

When I specify the numeric asset name for RUMPSHAKER.IN.YA.FACE, then it works
![image](https://user-images.githubusercontent.com/376028/74898024-865c3b00-534d-11ea-8432-6bda480434b1.png)

**Comment by cryptcoin-junkey** [comment]
It will be fixed by https://github.com/jdogresorg/counterparty-lib/commit/25bbe4dcc871552e203405b8d2cec1286c74e9b2

**Comment by chiguireitor** [comment]
Fixed in develop
