### ISSUE TITLE
dispensers - creating unnecessary records

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1071]
I have found an issue with dispensers. Specifically when an address has multiple dispensers setup on the same address. Any send of BTC will trigger a "dispense" transaction in the database from EVERY dispenser setup on the address, even if the dispenser minimum satoshi rate was not met.

This behavior is resulting in a bunch of unnecessary writes to the database of 0 quantity values and contributing to bloating the CP database.

Here is an example transaction
https://testnet.xchain.io/tx/ac8f10ae37df6bf6c12f25186e40fc7054a7c9dadd80a094818d2ed4353466b5

In this transaction there were 4 dispensers setup. 
3 dispensers were setup to trigger/vend on 0.001 BTC
1 dispenser was setup to trigger/vend on 0.0001 BTC

![image](https://user-images.githubusercontent.com/376028/75642435-626fe380-5bf0-11ea-9586-45edf4607933.png)

0.0001 BTC was sent to the address and only the BACONTITS dispenser should have done a dispense. Instead we have the 3 other dispensers creating 'dispense' records with 0 quantity.
![image](https://user-images.githubusercontent.com/376028/75642444-6ac81e80-5bf0-11ea-8383-daa9caa74d4e.png)

**Comment by chiguireitor** [comment]
Fixed on develop
