### ISSUE TITLE
create_send - MPMA support for subassets

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1072]
The current create_send documentation indicates that you can specify an asset or subasset, however I am unable to specify a subasset name when creating an MPMA transaction and get an error

![image](https://user-images.githubusercontent.com/376028/75747987-39744f00-5cd3-11ea-9648-019ff5a02c13.png)

**Comment by cryptcoin-junkey** [comment]
It will be fixed by https://github.com/jdogresorg/counterparty-lib/commit/3fb9fc4e66699eeca5241707eedf2a49127c5585

**Comment by chiguireitor** [comment]
Fixed on develop
