### ISSUE TITLE
Remove Dust from asset ownership transfers

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1073]
Currently if I do an asset ownership transfer between addresses, the transaction that is generated includes a dust output of 5340 satoshis. We should stop wasting BTC by sending BTC dust on asset transfers.

Here is an example asset transfer on xchain:
https://xchain.io/tx/357830c9fa54f7a80df0d1d6c4ca8641204ae0e7e0fed5493faf2457e09d2ab9

Here is the same transaction on blockstream, where you can see the dust output
https://blockstream.info/tx/357830c9fa54f7a80df0d1d6c4ca8641204ae0e7e0fed5493faf2457e09d2ab9

**Comment by chiguireitor** [comment]
I think this would new a new message type, as asset transfers don't include a field for destination (they are just issuances) and rely on the first UTXO address as marker for the transfer destination.
