### ISSUE TITLE
Upgrade python-bitcoinlib.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [CounterpartyXCP/counterparty-lib#1079]
Hello,

Finally [new python-bitcoinlib v0.11.0](https://github.com/petertodd/python-bitcoinlib/releases/tag/python-bitcoinlib-v0.11.0) with bech32 support was released.
I'm checking it with Monaparty chain.  It looks working fine.

**Comment by chiguireitor** [comment]
Excellent, it's a minor version bump tho, have to check if it doesn't breaks anything else.

**Comment by adamkrellenstein** [comment]
Fixed
