### ISSUE TITLE
[Q] Length limit of the issuance description, 42 or 52 ?

### ISSUE THREAD

**Issue by cryptcoin-junkey** [CounterpartyXCP/counterparty-lib#1093]
Reffering to https://counterparty.io/docs/api/#create_issuance , 

> description (string, default=’‘): A textual description for the asset. 52 bytes max.

The other hand, https://github.com/CounterpartyXCP/counterparty-lib/blob/52d3f07593880d27d5b714af6f62ccc50b86d0a6/counterpartylib/lib/messages/issuance.py#L243-L245

```
if len(description) > 42:
```

It seems be inconsistent.

**Comment by jdogresorg** [comment]
I went ahead and updated the documentation to indicate what code is enforcing, 42 bytes.

Once the documentation PR is merged, i'll run the scripts to update the counterparty.io api docs

**Comment by cryptcoin-junkey** [comment]
I see the valid is 42. I close here as resolved.

**Comment by cryptcoin-junkey** [comment]
Let me reopen here.  I was a little bit confused.

```
if not (block_index >= 317500 or config.TESTNET or config.REGTEST):  # Protocol change. 
```

So there have been no limit since `block_index == 317500`, right?

**Comment by jdogresorg** [comment]
Now that I am looking a bit closer at the length of asset descriptions, yes, no limit since block 317500... I'll update the docs to remove the limitation note.

**Comment by cryptcoin-junkey** [comment]
Thank you for the comment. @jdogresorg 
I close here again.
