### ISSUE TITLE
zero dividend error - create_dividend

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1104]
Occasionally users will complain about getting 'Zero dividend' errors when trying to pay out dividends.

Here is an instance of that behavior... 

Problem Request
---
```
{
	"method": "create_dividend",
	"params": {
		"source": "1BH9sBVQ645gx2D3pfkc95SSvvEXpFhw2N",
		"asset": "PEPEYES",
                "dividend_asset": "STPEPESUNC",
		"quantity_per_unit": 3,
		"fee": 30277,
		"allow_unconfirmed_inputs": true
	},
	"jsonrpc": "2.0",
	"id": 0
}

```
Problem Details
---
There are 9 holders of PEPEYES tokens and there are 600 STPEPESUNC tokens issued... so, the dividend SHOULD work and pay out 3 STPEPESUNC to every holder of 1 token of PEPEYES.... instead we get a 'zero dividend' error returned

https://github.com/CounterpartyXCP/counterparty-lib/blob/765c00b76857d4181bf69a4ddd5b592790073689/counterpartylib/lib/messages/dividend.py#L110

The repo code seems to indicate that 'zero dividend` is thrown when there are no holders, yet clearly there are 9 PEPEYES holders... so what is going on?!?!

![image](https://user-images.githubusercontent.com/376028/105231711-22716200-5b1c-11eb-803b-815dc3e1ddc0.png)

**Comment by jdogresorg** [comment]
After some investigation, it appears that the issue is that for non-divisible assets config.UNIT is set to 100000000 instead of 1

So, when we hit this line

https://github.com/CounterpartyXCP/counterparty-lib/blob/765c00b76857d4181bf69a4ddd5b592790073689/counterpartylib/lib/messages/dividend.py#L102

instead of calculating 
`    dividend_quantity /= 1`
we are doing
`        dividend_quantity /= 100000000`

this is why the `dividend_quantity` is being returned as 0 for all holders, resulting in the 'zero dividends' error

**Comment by jdogresorg** [comment]
after some further investigation, I think my fix is not good as we have

**Comment by chiguireitor** [comment]
Yes, the fix seems to affect adversely divisible asset dividends

**Comment by jdogresorg** [comment]
The fix appears to be working :)
![image](https://user-images.githubusercontent.com/376028/107824545-827fb080-6d36-11eb-88cb-650424adc64a.png)

**Comment by longhoangwkm** [comment]
I still got this error on testnet

**Comment by longhoangwkm** [comment]
cc @jdogresorg

**Comment by chiguireitor** [comment]
Think we didn't rebuild the testnet images, what server were you using?

**Comment by jdogresorg** [comment]
The issue is your trying to pay out a dividend on VACUZ and there are no holders of VACUZ except the issuer.

![image](https://user-images.githubusercontent.com/376028/108221126-4ceb1680-70ec-11eb-923a-aee8a74bcb20.png)

In order for you to issue dividends, you need to have holders to pay the dividend payment to. In this case, since you have 0 VACUZ holders (except the issuer), Counterparty is throwing the correct error letting you know that your request would result in `zero dividends`.

Try again except use an asset that has holders this time :)

**Comment by longhoangwkm** [comment]
Thanks for explaining, It's possible if we can raise `no holder` error for more clearly meaning
