### ISSUE TITLE
non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)

### ISSUE THREAD

**Issue by adilcnn** [CounterpartyXCP/counterparty-lib#1124]
Hello,
Just discussed over Telegram, I am unable to move BTC from a Segwit address:

bc1qv3p7cqmqxaytxau8fvyy3t436vvqhzn2yrq39x

The Signed Message is:

signed transaction= 020000000001012953ec299c5f09a021566f6785261cc63a852d70bfb89f1d0443a0882f7be28e0000000000ffffffff02887e0300000000001976a91419ee5a815d25dbe0cc41c3c2e9c784395fe7931a88acd2260000000000001600146443ec03603748b377874b0848aeb1d3180b8a6a02483045022100e063c933d54e793dfb4eb56323975bb52ad3b9b0cb7c8cf418bfd962fe7a80c202201573396206ad78350565e81f8ce7fcb4964a123089a46a26f39b7b138790cd42012102b71c3cba3b4ceaf71667192bc3613f5525c12a54d4a14a21193bb834c0a612e400000000

**Comment by jdogresorg** [comment]
The error being thrown when trying to broadcast this transaction is :
Code: -26, Error: non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)

1.) the image did not come through

2.) have you tried importing the private key for the address into electrum and moving the BTC that way?

3.) I believe you should be able to move the BTC using electrum, and that this is just a signature issue with counterparty, not an issue in general with using segwit addresses on Bitcoin.... please try step #2 suggested above and report back.

**Comment by adilcnn** [comment]
I used Electrum but it shows “this is watch-only wallet” cannot be used to move funds, I used Windows, I think it’s not working fine with windows or may be one reason or the other.

**Comment by jdogresorg** [comment]
tracking the issue back to core issue being incorrect value being encoded for the UTXO when signing... and utxos balances are coming from addrindexrs.

looking into a fix... but at least we have identifed the core issue (wrong btc balance value being returned by addrindexrs) and are working on solution

**Comment by jdogresorg** [comment]
Tracked this issue down to invalid value data in for utoxs in `get_unspent_txouts` API requests. 

Fix is in PR request https://github.com/CounterpartyXCP/counterparty-lib/pull/1127

Testing fix manually on 3 production servers before merging fix in and closing this issue

**Comment by adilcnn** [comment]
Ok thank you sir, what should I do now?

**Comment by jdogresorg** [comment]
try sending the BTC out of your address at bc1qv3p7cqmqxaytxau8fvyy3t436vvqhzn2yrq39x and let us know if it worked for ya.

**Comment by adilcnn** [comment]
Great sir it worked, withdrawal successful, thank you so much for supporting.

**Comment by adilcnn** [comment]
My other 2 issues are pending but I think those scheduled next month, should I close this issue?

**Comment by pssdaop** [comment]
When trying to withdraw my BTC or an NFT from my segwit address, I receive an error:

Error making request to UNKNOWN/Default: JSON-RPC Error:
Type: Server error

Code: -32000

Message: Bad status code returned: '500'. result body: '{"result":null,"error":{"code":-26,"message":"non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)"},"id":0} '.

Here´s some of the fixes I have tried to do:

- Export private key to another wallet = for some reason, the segwit address has no option to "Show private key", like for some other addresses.
- Use a mnemonic converter to get the private key. = Not compatible seed.
- Import seed into segwit specific wallet = Not compatible seed
- Import seed into Freewallet = Works, but cannot access the address/holdings
- Import seed into Electrum = It seems to work, however I am not able to access my address either

**Comment by jdogresorg** [comment]
In freewallet you should be able to export the private key by pulling up the "Change Address" box, then right-clicking on the segwit address you wish to view the private key for and selecting "View Private Key"... this should allow you to export the private key for the address in question.

FYI.. the wallet passphrase/seed will not work in other wallets as the wordlist and address derivation path used in freewallet and counterwallet is slightly different than other wallets.

**Comment by pssdaop** [comment]
> 
> 
> In freewallet you should be able to export the private key by pulling up the "Change Address" box, then right-clicking on the segwit address you wish to view the private key for and selecting "View Private Key"... this should allow you to export the private key for the address in question.
> 
> FYI.. the wallet passphrase/seed will not work in other wallets as the wordlist and address derivation path used in freewallet and counterwallet is slightly different than other wallets.

As I noted above, I have unfortunately already tried this to no avail. Seeds is imported correctly, however I can´t access the actual segwit address with my funds. The bc1 address is nowhere to be found, even after importing the seed and also trying with the "add new address" button. 

Also, I am currently suddenly having issues with logging in to counterwallet. The loading bar goes on but I do not get logged in.

**Comment by jdogresorg** [comment]
seed is the passphrase... private key access individual addresses

If you were able to export the PRIVATE KEY for the address in freewallet (which you seem to indicate you did), then you should be able to import the PRIVATE KEY into a wallet like electrum and use the bc1 address associated with it.

Also counterwallet is old/outdated, so you should use a modern wallet like freewallet.io DESKTOP wallet

If you continue to have this issue with the transcation, click the freewallet logo, click the debug icon, then try your action again... then try your transaction again and copy/paste the "Signed tx=" line from freewallet and paste it here so we can see exactly what address your having issues with and the SPECIFIC transaction that your having issues with.

Also in the future please be more descriptive with what wallet your using and exactly what it is your trying to do.... it is not clear from your post above if your using electrum or freewallet when trying to export the PRIVATE KEY (not sure counterwallet even allows exporting the private key of BC1 addresses)
