### ISSUE TITLE
"Insuficient BTC at address" error. 

### ISSUE THREAD

**Issue by jsgalt** [CounterpartyXCP/counterparty-lib#1126]
So, I've gotten this error a couple of times now. 
![image](https://user-images.githubusercontent.com/9690531/130713967-36276e59-0315-403a-9810-37f7e8bd4d8a.png)

The error happened when trying to buy a rare pepe off the DEX with pepecash. The only amount of BTC needed to make the transaction was about 2000 satoshis, but the wallet failed anyway.

The address signing the transaction had well over 0.004 btc in it, more than enough to make the transaction. 

J.dog suggested getting the balance to over 0.01 btc, to bypass the error for now. 

His suggestion worked and I was able to buy pepe.

**Comment by jdogresorg** [comment]
this issue should be fixed with commit cc6a024 which handles reconnecting counterparty to addrindexrs when a connection is lost/dropped/timed out
