### ISSUE TITLE
scriptsig-not-pushonly

### ISSUE THREAD

**Issue by uwutm888** [CounterpartyXCP/counterparty-lib#1130]
Sending XCP from a 3 address using Postman and Electrum showing 'scriptsig-not-pushonly' error.

No problem connecting to CP API with Postman.

Request:

{
    "method": "create_send",
    "params": {
        "source": "3B6T4ZWJGNRkGn8HGan9djo5zKqsW7qT1c",
        "destination": "1AWHc5TiEmxrEKVUzB5pBhX9HkJH2xb2TL",
        "asset": "XCP",
        "quantity": 302,
        "allow_unconfirmed_inputs": true,
        "fee": 1000
    },
    "jsonrpc": "2.0",
    "id": 0
}

Unsigned transaction:

{
    "result": "01000000018ded115063ddd398243f56dd361f663af991c00940c7147054ba369664ffe0310000000017a9146727aefad776145ff8899b82076fd793dbbfb09d87ffffffff020000000000000000306a2ed9a5b23094f30a035ce5dac276da05aae3928a3c8e5dcc0ca62cdb0056cfdcd619c7e7bffdf892869fa9a9afebdb9bbd02000000000017a9146727aefad776145ff8899b82076fd793dbbfb09d8700000000",
    "id": 0,
    "jsonrpc": "2.0"
}

![Postman 2](https://user-images.githubusercontent.com/89569044/131415585-cba027db-38a0-4dc2-ab33-127d729d3942.jpg)

Loading transaction from text on Electrum:

01000000018ded115063ddd398243f56dd361f663af991c00940c7147054ba369664ffe0310000000017a9146727aefad776145ff8899b82076fd793dbbfb09d87ffffffff020000000000000000306a2ed9a5b23094f30a035ce5dac276da05aae3928a3c8e5dcc0ca62cdb0056cfdcd619c7e7bffdf892869fa9a9afebdb9bbd02000000000017a9146727aefad776145ff8899b82076fd793dbbfb09d8700000000

![Load transaction](https://user-images.githubusercontent.com/89569044/131415849-33cebc87-5870-43bd-b66f-5e8b6276f229.jpg)

Shows transaction already signed:

![Broadcast](https://user-images.githubusercontent.com/89569044/131415957-ca0872b3-2184-45e3-8520-ace977bb1c86.jpg)

And when trying to broadcast it the 'scriptsig-not-pushonly' error appears:

![Broadcast Error](https://user-images.githubusercontent.com/89569044/131416099-a24eabb7-04c3-4317-9b9f-5ceb75a59215.jpg)

**Comment by jdogresorg** [comment]
closing issue. Please re-open if issue persists.
