### ISSUE TITLE
BTC orders not moving to 'filled' status when order is completed

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1135]
It seems that orders for BTC on the DEX are staying with status set to 'open' even though the order has been filled.

https://xchain.io/tx/1711494

Below you can see that the order has executed and there is nothing left to sell in the order, yet the order status remains 'open'
![image](https://user-images.githubusercontent.com/376028/135525083-19ebad9c-ac67-4a30-9476-c6b8fef79b16.png)

When placing orders for native assets (not BTC), then when an order executes, it is marked as 'filled'

https://xchain.io/tx/1715581
![image](https://user-images.githubusercontent.com/376028/135525710-4ba689b5-61a2-4103-9657-165918576f22.png)

After some digging in the `messages` table, it seems for normal orders we do an update of the `orders` table to move status to 'filled'... however when dealing with BTC orders, we do not do an update of the `orders` table to set status to filled.

**Comment by hexatomium** [comment]
This seems to be by design according to this: 
 https://counterparty.io/docs/protocol_specification/

"Because order matches pending BTC payment may be expired, orders involving Bitcoin cannot be filled, but remain always with a status open."
