### ISSUE TITLE
ripemd160 not supported in newer versions of openssl

### ISSUE THREAD

**Issue by windsok** [CounterpartyXCP/counterparty-lib#1178]
Newer versions of openssl removed the `ripemd160` hash function, which python's `hashlib` relies on.

When running counterparty on newer OS like Ubuntu 22.04 with recent openssl  we see the error 
```
ValueError: unsupported hash type ripemd160
```

This is a similar issue to https://github.com/bitcoin/bitcoin/issues/23710

**Comment by adamkrellenstein** [comment]
Fixed
