### ISSUE TITLE
`balances` API endpoint incorrectly associating assets with collections they are not a part of

### ISSUE THREAD

**Issue by btroia** [CounterpartyXCP/counterparty-lib#1189]
Hi! When an API request is made to the `balances` endpoint, some assets being returned are incorrectly being associated with a collection (particularly Spells of Genesis):

To reproduce:

1. Make request to https://xchain.io/api/balances/1DDEJ8E7qmeL2uvY8yaRSjrfHQb8wkrAvF?page=2&limit=3

2. In the response, notice that BONUSBTC and BUYINGFDCARD are incorrectly being associated with the spells-of-genesis collection (in the `collections` field):

```
{
    "address": "1DDEJ8E7qmeL2uvY8yaRSjrfHQb8wkrAvF",
    "data": [
        {
            "asset": "BLOCKTRAILCD",
            "asset_longname": "",
            "collections": [
                "spells-of-genesis"
            ],
            "description": "SOG card",
            "estimated_value": {
                "btc": "0.04167500",
                "usd": "942.50",
                "xcp": "250.00000000"
            },
            "quantity": "10"
        },
        {
            "asset": "BONUSBTC",
            "asset_longname": "",
            "collections": [
                "spells-of-genesis"
            ],
            "description": "Claim Your Bonus +1,000 XCP /+0.6300 Bitcoin (BTC) Visit >> https://counter-event.org",
            "estimated_value": {
                "btc": "0.00000000",
                "usd": "0.00",
                "xcp": "0.00000000"
            },
            "quantity": "0.63000000"
        },
        {
            "asset": "BUYINGFDCARD",
            "asset_longname": "",
            "collections": [
                "spells-of-genesis"
            ],
            "description": "I wanna buy your FDCARD. Add me on twitter: @valor4ever89 or Telegram: @valor4ever89",
            "estimated_value": {
                "btc": "0.00000000",
                "usd": "0.00",
                "xcp": "0.00000000"
            },
            "quantity": "1"
        }
    ],
    "total": 32
}
```

3. However, when viewing the asset on xchain.io, it is (correctly) not associated with the Spells of Genesis collection:

https://xchain.io/asset/BONUSBTC

**Comment by jdogresorg** [comment]
This is an issue on xchain.io with the custom API I created, not a counterparty-lib specific issue, so this is not the correct place to report this issue.

in the future if you have an issue on xchain, please contact me directly via email at j-dog@j-dog.net or on telegram at http://t.me/jdogresorg

I have verified this issue exists and have fixed it (I was not resetting the projects array properly, now I am)
