### ISSUE TITLE
new message type for new issuance format

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1221]
In the last release we modified an existing issuance message type format to remove the callable fields when we SHOULD have just rolled out a new message type with the new format.

In the next release we should do the following:
1. Restore the old message format which includes the callable fields again
2. Create new issuance message type with new format with the callable fields removed, and support for the new `reset` field

This would be a cleaner way to undo the format change updates than the "hack" that we have in this PR to make things work nicely.
https://github.com/CounterpartyXCP/counterparty-lib/pull/1219

**Comment by Jpja** [comment]
I agree on creating a new issuance message, and I think more improvements can be implemented at the same time. I will open a forum thread.

**Comment by jdogresorg** [comment]
addressed in PR #1258 which has been merged and will be in the upcoming 9.60.3 release

**Comment by jotapea** [comment]
@jdogresorg Can you help clarify [this](https://github.com/CounterpartyXCP/counterparty-lib/pull/1258#issuecomment-1776168529)?
