### ISSUE TITLE
Asset description deleted when `null`

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1224]
Joe Looney and a couple other users have reported that any issuances where the asset description is set to `null` results in the asset description being overwritten. This is undesirable behavior, as it requires the asset issuer to encode the asset description in every issuance transaction, making the transaction larger and more expensive.

Issuance tx where `description` is removed when `null`
https://xchain.io/tx/2225314

I think we should update the default behavior to :
1. If `description` is set to `null`, asset description is left un-touched
2. If `description` is set to `''`, asset description is removed / updated

This will allow users to only include their asset description when they actually want to update it, and give them an option to remove the description entirely by specifying `''`

**Comment by jdogresorg** [comment]
Should be addressed in PR #1262

**Comment by jdogresorg** [comment]
closing. fix ill be in next release 9.61.0

**Comment by Jpja** [comment]
This will open up a new spam vector. The way the DB works is that for every new issuance to an asset, the description is saved over again in a new row. But the user has also had to re-encode the description in a new BTC tx. This has ensured a proportional fee.

We should allow `null` to duplicate the asset description AFTER we optimize the DB.
