### ISSUE TITLE
Constant MempoolError exits counterparty

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-lib#1227]
I'm unable to keep counterparty-lib up for a long time. Getting the following error continuously:

```
federatednode-counterparty-1  | [2023-03-10 06:29:46][INFO] Block: 780110 (15.06s, hashes: L:14a2d / TX:89a76 / M:f4265)
federatednode-counterparty-1  | [2023-03-10 06:29:51][INFO] Mempool cache initialized: 4.84s for 20,000 transactions
federatednode-counterparty-1  | [2023-03-10 06:29:51][INFO] Ready for queries.
federatednode-counterparty-1  | [2023-03-10 06:30:11][ERROR] Unhandled Exception
federatednode-counterparty-1  | Traceback (most recent call last):
federatednode-counterparty-1  |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1547, in follow
federatednode-counterparty-1  |     raise MempoolError
federatednode-counterparty-1  | counterpartylib.lib.blocks.MempoolError
federatednode-counterparty-1  | 
federatednode-counterparty-1  | During handling of the above exception, another exception occurred:
federatednode-counterparty-1  | 
federatednode-counterparty-1  | Traceback (most recent call last):
federatednode-counterparty-1  |   File "/usr/local/bin/counterparty-server", line 11, in <module>
federatednode-counterparty-1  |     load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
federatednode-counterparty-1  |   File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
federatednode-counterparty-1  |     server.main()
federatednode-counterparty-1  |   File "/counterparty-cli/counterpartycli/server.py", line 174, in main
federatednode-counterparty-1  |     server.start_all(db)
federatednode-counterparty-1  |   File "/counterparty-lib/counterpartylib/server.py", line 494, in start_all
federatednode-counterparty-1  |     blocks.follow(db)
federatednode-counterparty-1  |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1555, in follow
federatednode-counterparty-1  |     raise MempoolError
federatednode-counterparty-1  | apsw.BusyError: BusyError: database is locked
federatednode-counterparty-1 exited with code 0
```

Restarting counterparty works up until it re-syncs, but then the error repeats.

**Comment by jotapea** [comment]
The problem seems to be related to having heavy reads of the SQLite database. Even though this is something the protocol COULD improve, its not necessarily its responsibility based on the current architecture. Maybe this is a reason why the protocol includes a limited data reading api. Closing this issue.

**Comment by jotapea** [comment]
Reopening this issue. The situation has gotten worse, even after making some caching improvements in [xcp.dev](https://xcp.dev). @jdogresorg I also see that [xchain.io](https://xchain.io) is having similar issues, showing (confirmed) data from 2 days ago in the 'Unconfirmed' view.

**Comment by jdogresorg** [comment]
@jotapea There is no issue with xchain.io or with `counterparty-lib` parsing that I am aware of. There IS a known issue in Counterparty where under heavy mempool loads (like we have been having for the past 3+ days with 120k+ pending transaction) CP mempool is not updated as frequently.... so pending txs dont show up in, or expire as quickly from the CP mempool... but parsing continues on perfectly fine, blocks are parsed without any issues.

In the future, if you have questions about if xchain.io is behind, best to check https://xchain.io/blocks as that will tell you the latest blocks parsed by xchain and CP. 👍 

This issue your reporting here is not being seen on any other nodes I run (about 10). I've setup 4 new servers / fednodes in the past 2 weeks, also am aware of others playing with nodes on windows and not seeing these syncing issues elsewhere. 

Perhaps this is an issue with your local config? Maybe @pataegrillo has some insight as to why your local sqlite database keeps getting `locked`

**Comment by jdogresorg** [comment]
Here is the known mempool update issue of which I speak :) 

https://github.com/CounterpartyXCP/counterparty-lib/issues/1111

**Comment by jotapea** [comment]
@jdogresorg I also don't see problems with the mined blocks. This issue is specifically about the mempool, and it does seem to be connected to your experience in #1111, thanks for linking to it.

I am running a single node which is syncing + getting read hits, but I assume you are doing load balancing with your multiple nodes, correct? Are your fednode configurations used straight from the fednode repo code, or are you making any adjustments? I tried adding `maxmempool=1024` to the bitcoin.conf but the problem persists...

**Comment by jdogresorg** [comment]
The issue subject and post on the topic seem to indicate your having an issue with CP exiting/crashing when trying to parse the mempool.... Not seeing that behavior here... CP here is not crashing or needing restarts, it is just not updating mempool as often as it should.

As to your question about my fednodes, all fednodes I run are straight from the cp repo, no adjustments at all except for a couple IP bindings on a couple servers.... other than that no changes.

Curious if your running the `full` or `base` config..... if running `full`, could be counterblock beating on counterparty... def strange behavior tho.... only time i've seen the database lock/exit issue similar to originally described is when doing a database sanity check and bailing out early... think the database remained locked until the sanity check was completed.

**Comment by jotapea** [comment]
I got the minimal `base` config. Only mainnet bitcoin, addrindexrs and counterparty running.

**Comment by jotapea** [comment]
Found the root cause of this issue.

First, there is a direct correlation between the `maxmempool` config and the time it takes for the `mempool` table to be populated. In hindsight this is obvious, so, is better to leave the `maxmempool` config unset (defaults to 300MB) or make it even lower for the `mempool` table not to get locked for so long.

But still, because lately the mempool has so many unconfirmed transactions, the approach of locking the DB to fill out the `mempool` table is not ideal.

My belief is that counterparty-lib needs to slim down its responsibilities as much as possible. So, I would just remove the `mempool` table entirely.

Then, to provide some sort of alternative into the same counterparty-lib **api**, have an in-memory solution. But even this is optional, because the main responsibility of counterparty-lib is the block transactions, which are the ones that generate the consensus hashes.

[CNTRPRTY/counterparty-lib](https://github.com/CNTRPRTY/counterparty-lib/tree/master_cntrprty961) will be following this approach (commits: https://github.com/CNTRPRTY/counterparty-lib/commit/77e5c7f661039db9714a3a49666d9307a952a05c and https://github.com/CNTRPRTY/counterparty-lib/commit/aa9a375b326712a4f87a627054c96ab1c14c85b8) to the mempool, and it being tested live in [xcp.dev](https://xcp.dev). So far it is running smoothly (but can still be improved), so maybe this is something the reference protocol can also adopt. Feel free to cherry pick it, or let me know if I should make this a PR.
