### ISSUE TITLE
Dispense BTC 

### ISSUE THREAD

**Issue by stet** [CounterpartyXCP/counterparty-lib#1231]
https://github.com/CounterpartyXCP/counterparty-lib/blob/032c0d322646d191ea7c379f8ac59c7ab628fcaa/counterpartylib/lib/messages/dispenser.py#L86

It might be worth discussing conditions to allow automated dispense of BTC rather than absolute disallow. 

One use case is to add more logic around overpayments and track dispenser close time with payment transaction times. Also BTC for BTC is good for tests and some fringe use cases.

**Comment by jdogresorg** [comment]
L2s are not able to escrow funds from L1... ie, Counterparty can not escrow BTC in a dispenser, because BTC lives on L1... Counterparty can only escrow its own tokens (L2).

This is a technical limitation, not a design decision.

**Comment by jdogresorg** [comment]
If you would like to discuss improvements to counterparty, please do so via the correct process which is the Counterparty Improvement Proposal.

Here is a link to the process for making improvements to counterparty.
https://github.com/CounterpartyXCP/cips


Here is where discussions about dispensers and possible feature enhancements are being discussed
https://forums.counterparty.io/t/cip21-dispensers/5488

**Comment by stet** [comment]
This was no suitable for a CIP yet. 
My main interest is not nec escrow btc but rather automatically return (btc) to sender. 
I will discuss on forum or telegram.
