### ISSUE TITLE
Cannot lock and change description at once

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/counterparty-lib#1239]
When locking an existing asset (using the lock flag), the description from the message data is ignored. The old description is copied instead.

This is likely inherited from when the LOCK keyword was used in the description field.

**Comment by jdogresorg** [comment]
Can confirm this is known issue which needs addressing.

**Comment by jdogresorg** [comment]
I believe PR #1265 addresses this issue.

**Comment by jdogresorg** [comment]
Fix will be in upcoming v9.61.0 release.
