### ISSUE TITLE
Tx included in v9.60.1 but not in v9.60.2

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/counterparty-lib#1240]
This dispense is shown on xcp.dev - https://www.xcp.dev/tx/16bd438b1dee6b1f750758eeabef7a876c204082a088c48ca51c416d6651d5db

It is not a Counterparty tx according to xchain - https://xchain.io/tx/16bd438b1dee6b1f750758eeabef7a876c204082a088c48ca51c416d6651d5db

This happened on block 790339. The hashes match until the previous block 

Xcp.dev runs on v9.60.1 and xchain on v9.60.2.

v9.60.2 is a minor update, thus a difference in consensus code is not expected.

**Comment by jdogresorg** [comment]
Confirmed, no tx appears in 9.60.2 database for the above tx

```
root@sites:/home/jdog# sqlite3 federatednode/data/counterparty/counterparty.db
SQLite version 3.37.2 2022-01-06 13:25:41
Enter ".help" for usage hints.
sqlite> select count(*), sum(length(description)) from issuances where description like 'stamp:eyJwIjogInNyYy0yMC%';
16015|1448298
sqlite> select * from dispenses where tx_hash='16bd438b1dee6b1f750758eeabef7a876c204082a088c48ca51c416d6651d5db';
sqlite> 

```

Will dig into this issue on Monday (flying today) and once issue is resolved, will put out fix and numeric xcp fee.
