### ISSUE TITLE
CORS blocked on api.counterparty.io but not on public.coindaddy.io

### ISSUE THREAD

**Issue by Iheff** [CounterpartyXCP/counterparty-lib#1247]
didnt quite know where to put this so settled on main repo as its a general thing.
I always notics that I am CORS blacked when requesting from api.counterparty in comparison to public.coindaddy where i can freely make Front end based JS requests
On noting this Was asked to provide a deomontrable isolated case for examination as it seems we dont think there should be CORS blocking on api.counterparty and also doesnt seem that way from seeing Freewallet requests.

have provided a sample here of an example where I run into this issue.

https://codepen.io/ndlbl/pen/poQERRm?editors=1111

(open the console tab at bottom left to see logging, youll see one request that goes through and reports succes - and youll see one incident that cant back a response, opening dev console to view this request you will notice a message about CORS blocking in the OPTIONS request, a faux request that clears the POST to go on)

Kind regards Indelible.

**Comment by jdogresorg** [comment]
After reviewing your code.... it appears your making an HTTPS request to an HTTP port..

port 4000 = http
port 4001 = https

Please review the API ports and info at https://api.counterparty.io/

**Comment by Iheff** [comment]
Hiya, changing to https://api.counterparty.io:4001 certainly seems to have had the desired effect - however, when utilising http://api.counterparty.io:4000 the issue with CORS warnings does persist.

Of course I am super satisfied that I am no longer CORS blocked on the https, but have adjusted the codepen to reflect the suggested fix and also the faling variant.

https://codepen.io/ndlbl/pen/poQERRm

Thank you!
