### ISSUE TITLE
APSW is available in PyPi

### ISSUE THREAD

**Issue by rogerbinns** [CounterpartyXCP/counterparty-lib#1249]
(I am the APSW author).  It has been [available in PyPi for 2 years now](https://pypi.org/project/apsw/#history), so you can simplify your [setup.py](https://github.com/CounterpartyXCP/counterparty-lib/blob/71ff5f0b953237cd72012c111ec102954aa170f0/setup.py#L21)

**Comment by adamkrellenstein** [comment]
Ach thank you!
