### ISSUE TITLE
CRITICAL ISSUE: master branch handling

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-lib#1275]
The `master` branch is getting changes merged without proper review by multiple developers (specially, federated node network peers). So, I believe we need to FOCUS on this CRITICAL issue (following up from https://github.com/CounterpartyXCP/counterparty-lib/pull/1256).

From my perspective of over a year observing protocol development activity, it seems @pataegrillo works on "orders" by @jdogresorg because his PRs have no descriptions (maybe is not "orders" but more of an agreement, but definitely these discussions are happening outside of the repo). Then, @jdogresorg merges these changes, effectively making a single person being responsible of the protocol code! I believe it is unacceptable (and dangerous!) for a supposedly decentralized protocol to have protocol affecting decisions made outside of the repository! Please let me know if I am incorrect in anything in this assessment. And more importantly, why the call to include more developers is being ignored.

And in a separate but VERY related note, the `master` branch is used by the [fednode](https://github.com/CounterpartyXCP/federatednode) software to [download the latest release](https://github.com/CounterpartyXCP/federatednode/blob/master/fednode.py#L337). Thus, this branch should not be an unstable non-consensus work in progress, instead it should be kept at the point of the latest stable "consensus"-agreed (we are not there yet, but assuming like it was) release (v.9.60.2) which is commit [09b20b3e](https://github.com/CounterpartyXCP/counterparty-lib/commit/09b20b3e1848481bed2fec3dba10c4cc11e5095e). 

Even if the current `master` branch is not being worked on in the way "I would [approach](https://github.com/CounterpartyXCP/counterparty-lib/pull/1270) it", please at least rename it. The new name could be something like `v9.60.3_rc_jj` (Release Candidate Jeremy Johnson).

Please don't ignore this critical issue. Or take it the wrong way, because my intention is to improve processes to have a better DECENTRALIZED network protocol.

**Comment by adamkrellenstein** [comment]
Yep. `master` branch is now locked.
