### ISSUE TITLE
Git branches cleanup

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-lib#1296]
While in the process of making a PR to the `develop` branch, I noticed that it has a huge "squash"-like commit (https://github.com/CounterpartyXCP/counterparty-lib/commit/a75e06fcdae10f75c3eb4adedac5d7d51fc38b16) with what seems to be all changes from 2020-10-30 to 2023-11-17, and coming from a forked repository (jdogresorg/counterparty-lib) instead of the `origin` (CounterpartyXCP/counterparty-lib).

I strongly suggest using a different strategy. A single commit with changes of more than 3 years is way past being useful. And at the very least, it should come from the `origin` official repo.

Maybe we could rename the old develop branch to something like `develop-legacy` and leave it at 2020-10-30. Then, just do a new `develop` branch coming up clean from the current `master`. Another option is to have release specific branches like`develop-9.61.2`.

(And on a separate but related note, we should also consider deleting some of the old branches...)

Thoughts? @jdogresorg @pataegrillo

**Comment by ouziel-slama** [comment]
> Maybe we could rename the old develop branch to something like develop-legacy and leave it at 2020-10-30. Then, just do a new develop branch coming up clean from the current master

+1

I am also of the opinion that the `master` branch must be made sacred. This will mean only using it for releases. And of course NEVER merge onto the master without all the tests passing (except for hot fixes meantime we fix all the tests).

**Comment by ouziel-slama** [comment]
if ok for everyone we can already delete the branches: `getsupply`, `spend_multisig_utxos`, `checktx`, `max-fee-fraction`, `tweaktest`.

**Comment by jotapea** [comment]
Ok by me. Made local copies for reference

**Comment by adamkrellenstein** [comment]
done!
