### ISSUE TITLE
Expand API to Support Block Explorers

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1299]
It seems that right now, if you want to create even a simple Counterparty block explorer, you first have to implement a lot of extra functionality in the backend. xchain.io has done this (closed-source), and xcp.dev more recently. It'd be much more efficient if at least the majority of the functionality were implemented in the core `counterpartyd` API, so as to encourage decentralization of the block explorer ecosystem and to avoid duplication of effort by downstream devs. This is especially important because xchain.io has had serious challenges supporting even moderate transaction volumes with their design.

It seems like a good place to start would be looking at <https://github.com/jdogresorg/counterparty2mysql> and  <https://github.com/CNTRPRTY/xcpdev>. We can populate some extra tables in SQLite, add the necessary indexes to make sure that common queries are performant, and then implement the additional API endpoints so that xchain.io and xcp.dev (if they like) could just run off of a vanilla `counterpartyd` backend, at least for basic usage.

If we want, we could put this feature behind a flag like `--explorer`.

See also https://github.com/CounterpartyXCP/cips/discussions/115

**Comment by jdogresorg** [comment]
ACK, great idea... fully support optimizing optimizing counterparty, and starting with xcp.dev as a base framework for explorer is fine... 

Also, if we make an explorer part of the fednode stack, the explorer repo should live in the main CounterpartyXCP repo, where changes are agreed upon via a consensus mechanism before being merged.... just like counterwallet, counterblock, etc.

**Comment by jotapea** [comment]
We are aligned ;)

**Comment by adamkrellenstein** [comment]
Replaced by #1359 and #1327 

Can re-open if the community requests particular endpoints or performance values.
