### ISSUE TITLE
Block parsing time anomaly

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-lib#1334]
**Describe the Problem**
While in the process of doing a rollback, in the "continue parsing" step, I noticed that block 822723 took 432.86s to process, instead of the usual ~5s for the blocks around it. Is not evident [why](https://www.xcp.dev/block/822723). May be a one off, or not and that is why I am reporting it.

**Steps To Reproduce**
1. Do a rollback to a block prior to 822723. I specifically ran `fednode rollback 819500 counterparty`, then `fednode start counterparty`.

**Screenshots and Logfiles**
![Screen Shot 2024-01-16 at 1 18 31 PM](https://github.com/CounterpartyXCP/counterparty-lib/assets/26850097/c14ecfaa-efbb-420b-bd3d-b19c57057310)

**Comment by adamkrellenstein** [comment]
so much has already changed. let's assume this was fixed
