### ISSUE TITLE
No `UPDATE`s

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-lib#1364]
This will allow clean and efficient rollbacks and reparses while reinforcing the immutability and verifiability of the Counterparty database.

- Remove all UPDATE in the code and only use INSERT.
- All tables already have a `block_index` and a `tx_index` to be able to retrieve the last valid row.
- This is already done for the `balances` table here https://github.com/CounterpartyXCP/counterparty-lib/tree/develop
- Keep API compatible with old structure
- Denormalize DB to make `BALANCES_VIEW_QUERY` optimized

**Comment by jotapea** [comment]
> This is already done for the balances table here https://github.com/CounterpartyXCP/counterparty-lib/tree/develop

Is it? isn't this part of https://github.com/CounterpartyXCP/counterparty-lib/pull/1349?

If it is still part of that PR, then I believe we should separate the balances changes into its own PR.

**Comment by jotapea** [comment]
And for posterity, while in principle I agree with the **ideal** of only having inserts, I don't think is practical to take such a definitive stance. Updates can still make sense for some functionality.

**Comment by adamkrellenstein** [comment]
<img width="657" alt="Screenshot 2024-02-02 at 7 44 13 AM" src="https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/403a4e38-c155-42b2-b6f7-8b3732d38876">

**Comment by jotapea** [comment]
So the bottom sql, that shows a `GROUP BY aa`, would not be needed? You would need to query by the concatenation itself then? I'm confused.

Such a simple table is getting so complicated.

Why not keep both approaches? A new `balance_history` that only does inserts and is best suited for the reorgs, rollbacks, etc. And keep `balances` as it exists now, which uses updates, but is read optimized? This one could get a new block index column to handle reorgs... but then we would just be doing the same work twice lol.

Whatever you decide I am fine, this is not a protocol change so worst case we can change it again in the future.

**Comment by adamkrellenstein** [comment]
Again, this is not complicated SQL, and using both approaches means having a higher complexity while giving up all of the advantages of the new architecture.

**Comment by jotapea** [comment]
I mean in comparison to how it was originally.

Maybe we could have the option to "build balances view" which can create the balances table as it existed before. This table could be optional and only for convenience, not used by the protocol itself. The protocol can rely only on the new "balances_history".

Anyway after re-reading I think I understand that now there will be a compound index of the concatenation and the rowid. Correct? Would this only benefit when querying by the first part, thus the address? What about when the query is by the asset?

**Comment by ouziel-slama** [comment]
A consolidated table is not necessary for the protocol and if someone needs one it is much cleaner to maintain it in a second database (client/server for example in the case of an explorer).
For the moment it is not necessary to denormalize the base by adding a field. `GROUP BY address, asset` works very well (see examples).

With the new table structure, generally speaking, queries should be of the following form:

To retrieve multiple rows

```
SELECT * FROM (
    SELECT *, MAX(rowid) AS rowid
    FROM <table>
    WHERE <immutable_fields>
    GROUP BY <id>
) WHERE <no_immutable_fields>
```

the more fields used in the where clause with immutable fields, the faster the query will be.

Or to retrieve a single row:

```
SELECT *, rowid
FROM <table>
WHERE <id>
ORDER BY rowid DESC
LIMIT 1
```

Examples:

```
SELECT * FROM (
    SELECT *, MAX(rowid) 
    FROM bets
    WHERE (feed_address = ? AND bet_type = ?)
    GROUP BY tx_hash
) WHERE status = ?
```

```
SELECT * FROM balances
WHERE (address = ? AND asset = ?)
ORDER BY rowid DESC LIMIT 1
```

```
SELECT address, asset, quantity, MAX(rowid)
FROM balances
WHERE address = ?
GROUP BY address, asset
```

This is finished in this PR https://github.com/CounterpartyXCP/counterparty-lib/pull/1349 so I am closing this issue.

**Comment by jotapea** [comment]
@ouziel-slama thanks for the details, and your work! Looking forward to run this version.

Thinking that as a reference implementation, your approach can make more sense. BUT in practical terms, as a separate non-reference implementation of the protocol (a fork repo), then it can make sense to have UPDATEs and the optional features I have been suggesting.

**Comment by ouziel-slama** [comment]
@jotapea thanks to you!!
I wouldn't recommend anyone to do this but yes it is possible! it is much cleaner, easier and safer to maintain a second database with a structure perfectly suited to your needs and to feed it with the API.

**Comment by jotapea** [comment]
Yeah is definitely safer to not touch it lol. Will make my decisions after working with it as is for a bit.
