### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-lib#1376]
What is the scope for the next release?

The code is having substantial changes done, but it seems none are protocol changing.

1. Is this assumption correct?
2. If it isn't, what specific changes affect the protocol?
3. If it is, when is the limit to plan for a stable release?

I want to start running the new optimizations, but I am not sure what is stable code. Also tried cherry picking some, like https://github.com/CounterpartyXCP/counterparty-lib/pull/1371/commits/291370b88a55ab6eee8ce249d4511fe0b0aa94f6 on top of [CNTRPRTY/counterparty-lib](https://github.com/CNTRPRTY/counterparty-lib), but it didn't work.

**Comment by adamkrellenstein** [comment]
good question! none of the changes in the pipeline are protocol changes (except for something like https://github.com/CounterpartyXCP/counterparty-lib/pull/1347 which one might call a backwards-compatible protocol change)

we've been merging protocol changes into `develop`, but the plan right now is to make a release only after we've identified, diagnosed and compensated for every consensus break with xchain.io (barring extreme, unforeseen challenges).

**Comment by jotapea** [comment]
What would you consider stable code which I can run for (testing with) xcp.dev? Or are we currently doing merges to `develop` in a way that can always be considered "stable"?

> we've been merging protocol changes into develop

I think you mean something like "code" here right? If not, then is contradicting the first message ;)

**Comment by adamkrellenstein** [comment]
sorry, yes! typo!

**Comment by jotapea** [comment]
Perfect thanks!

**Comment by adamkrellenstein** [comment]
Collecting issues in a new milestone: https://github.com/CounterpartyXCP/counterparty-lib/milestone/12
