### ISSUE TITLE
Kickstart LevelDB Lockfile on Testnet

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1423]
it looks like it's the same file for both mainnet and testnet

**Comment by ouziel-slama** [comment]
SQLite Lockfile ? you mean leveldb LOCK file ? kickstart don't use lock file.

**Comment by adamkrellenstein** [comment]
ach yes! 🤦‍♀️

**Comment by ouziel-slama** [comment]
the problem is that you had to pass `--bitcoind-dir=/.bitcoin/testnet3`. Fixed here https://github.com/CounterpartyXCP/counterparty-lib/pull/1433/commits/e7f104eef01525aeab941f386784477fdab633f4
