### ISSUE TITLE
Tweak Kickstart CLI

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1456]
With kickstart, don't say that the db will be deleted when it won't, e.g. `/home/adam/.local/share/counterparty/counterparty.db` will be moved to `/home/adam/.local/share/counterparty/counterparty.db.old` and recreated from scratch.

Should we default to `--resume-from=last`?

Should we just remove `--resume-from` and rely on `rollback` and then `kickstart` + default to resuming?

**Comment by ouziel-slama** [comment]
done
