### ISSUE TITLE
Data encoding method: P2SH

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#184]

**Comment by deweller** [comment]
Is this the official issue for adding the ability to send and receive assets from a P2SH address?

**Comment by dexX7** [comment]
@deweller: it's probably an issue for adding the ability to embed payloads into the scriptSig of pay-from-multisig-script-hash transactions.

**Comment by adamkrellenstein** [comment]
We can create a second issue for supporting P2SH addresses for things other than data encoding.

**Comment by deweller** [comment]
See https://github.com/CounterpartyXCP/counterparty-lib/issues/791

**Comment by rubensayshi** [comment]
closing, opened PR with implementation (https://github.com/CounterpartyXCP/counterparty-lib/pull/905) and CIP is being submitted for review 2day
