### ISSUE TITLE
Pylint check of entire codebase

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#535]
- Suggested options?! `--disable=line-too-long,bad-continuation,invalid-name,missing-docstring,logging-format-interpolation,logging-not-lazy`
- Integrate with Travis CI.
- Landscape?
- Scrutinizer? (see below)
##

**Comment by gotcha** [comment]
Reporting about cyclomatic complexity would be great as well.

**Comment by gotcha** [comment]
See https://scrutinizer-ci.com/g/gotcha/testcounter/code-structure/develop?elementType=py-function

**Comment by adamkrellenstein** [comment]
https://scrutinizer-ci.com/g/CounterpartyXCP/counterpartyd/inspections/6db16665-2cd5-4125-a9da-be55b46adfca

**Comment by adamkrellenstein** [comment]
See #1325 and #1305
