### ISSUE TITLE
Update `OP_RETURN` Size Limit to 80 Bytes

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#690]
Next version of Bitcoin Core should relay transactions with an 80-byte `OP_RETURN` output: https://github.com/bitcoin/bitcoin/pull/5286.

<s>Still probably can't make this the default encoding mechanism yet, because it'll be slower than multi-sig.</s> See #691.

**Comment by adamkrellenstein** [comment]
Oh, just because some minering pools have `OP_RETURN` support turned off, last I checked. If that ever changes, we can default to using `OP_RETURN` when the payload size is small enough.

**Comment by btcdrak** [comment]
@adamkrellenstein Mining pools mine `OP_RETURN`, there are no problems with it but until Bitcoin 0.11 rolls out, there is no point changing the encoding defaults because most nodes wont relay 80 byte `OP_RETURN`s

**Comment by adamkrellenstein** [comment]
@btcdrak, really? We can start using 40-byte `OP_RETURN`s now, then?

**Comment by btcdrak** [comment]
sure, 40-bytes relays and mines. There are a ton of services using `OP_RETURN` encodings already.

**Comment by adamkrellenstein** [comment]
As I said, last I checked, one of the big pools wasn't mining them, so there was often a delay.

**Comment by adamkrellenstein** [comment]
https://github.com/CounterpartyXCP/counterpartyd/blob/master/lib/transaction.py#L343

**Comment by btcdrak** [comment]
BTCGuild dont matter anymore, they are 3%. Eligius also blocks counterparty txs regardless.

**Comment by adamkrellenstein** [comment]
Haha. See #691.

**Comment by robby-dermody** [comment]
Closed, as this is implemented.
