### ISSUE TITLE
Look at Memory Usage

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#698]
##

**Comment by mtbitcoin** [comment]
The memory utilization for "counterparty-server.exe server" seems to be slightly on a the higher side of things

**Comment by adamkrellenstein** [comment]
I think the problem was the LRU cache params. I've just tweaked them. If that doesn't fix the problem, let me know.

**Comment by rippler** [comment]
I still see `counterparty-server` eat up 1GB of RAM. I checked the source, I did download the code with this changes. 
I tried to lower the changed values further and couldn't notice a difference (I didn't wait long, but working set size went over 125 MB, which it seems it's not supposed to do [(64 * 50 KB) + (16384 * 4KB)], and I also tried 16 and 16, respectively). 
Would it be possible to print cache details in the verbose mode?

**Comment by adamkrellenstein** [comment]
This is what `htop` shows me, after the server has been running for quite a while:
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
14962 adam       20   0  460M  152M  3724 R 26.6  3.9  1h06:27 /usr/bin/python /usr/bin/counterparty-server start
```

**Comment by adamkrellenstein** [comment]
Yeah, I'm pretty sure the only issue was the caches. When I disable them entirely, the memory usage is about 80 MB; when I enable them, it grows slowly to about 150 MB and stays right there. That all fits perfectly, given that `(64 * 50 KB) + (16384 * 4KB)` is 70 MB.

**Comment by rippler** [comment]
On Windows with the patch I'm seeing 365 MB working set size once `counterparty-server` has caught up and when it's idle. That's not too bad, although I did see it go to 1GB during the "catch up ingest" phase. 
On Linux I'm seeing better improvements as per Adam's note on this issue.

**Comment by adamkrellenstein** [comment]
Memory usage just spiked for me (to 711 MB), I think because of a reorg.

**Comment by adamkrellenstein** [comment]
Actually, it just spikes for me on tx construction?

**Comment by mtbitcoin** [comment]
I am back to about 1GB of ram consumed. The patches above did not seem to bring down the utilization. However, I have yet to encountered any crashes though

**Comment by cryptodock** [comment]
for me htop reports 2.8gb usage ( counterparty-server ) on ubuntu 14.04 , bitcoin 0.10, 21 active connections

**Comment by adamkrellenstein** [comment]
@ouziel-slama, you said you fixed this?

**Comment by ouziel-slama** [comment]
@adamkrellenstein, I fixed one problem with the raw transaction cache but the problem was in a code written after this issue was opened..
I continue to watch the memory usage on a dedicated instance, let me please watch it  one or two days before to close this issue.

**Comment by adamkrellenstein** [comment]
'k

**Comment by adamkrellenstein** [comment]
See `lock` branch.

**Comment by adamkrellenstein** [comment]
@robby-dermody, does your `lock` branch fix this?

**Comment by robby-dermody** [comment]
`lock` uses a different caching strategy in several places, but it still has caching (and for the raw tx cache, I expanded it to be larger). Let me observe the memory usage and see...

a possible option is making the most impactful tx cache size(s) user configurable, within a certain set of bounds, but that's probably not the best thing to do (could have possible hard-to-debug side effects)

**Comment by adamkrellenstein** [comment]
Caching is fine, as long as the case sizes are all bounded. (If there are, then there shouldn't be unbounded memory usage.)

What side-effects could changing the cache sizes have? That sounds dangerous...

**Comment by robby-dermody** [comment]
it's hard to tell the impact...that's why it's generally best to set, use, and test with a single set of well-tested parameters.

Current `counterparty-server` memory usage on Ubuntu is about 807MB resident after about 30 minutes running. If we see a situation where it's growing unbounded, I can perform some memory profiling/leak detection on it.

**Comment by robby-dermody** [comment]
With `lock` after running for a day or so, I'm seeing ~2.7GB resident. I can look into this more once I get past the caching issues.

**Comment by adamkrellenstein** [comment]
Yeah, that's a lot... :/

**Comment by unsystemizer** [comment]
Running `9.53.0 (develop)`: I also see a fair bit of RAM utilization on this idle mainnet instance (it's just keeping up with bitcoind, no other workload). 
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
26871 xcp       20   0 1198944 707424    112 D   1.0 71.0 149:16.21 counterparty-se
 1405 xcp       20   0  650556 139488      0 S   2.3 14.0   2250:33 bitcoind
```

**Comment by rubensayshi** [comment]
thats a lot less then mine xD

**Comment by littleskunk** [comment]
Running `9.55.1 (master)` on a QNAP NAS HS-251+ with only 2GB RAM is impossible.

Bitcoind with custom config file needs less than 200MB and can run as background service.

Counterparty-server needs more than 1GB RAM. Startup and shutdown are very slow. I can't run it as background service and have to stop it :(

**Comment by unsystemizer** [comment]
Been running both bitcoind  (mainnet) and counterparty-server (mainnet) on the same Rasberry 2 for a while, no issues, the both daemons stay up for months. 
```
Tasks: 138 total,   2 running, 136 sleeping,   0 stopped,   0 zombie
%Cpu0  :  3.8 us,  1.9 sy,  0.0 ni, 94.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : 96.4 us,  3.6 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  1.8 us,  0.0 sy,  0.0 ni, 98.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   942136 total,    11848 free,   377164 used,   553124 buff/cache
KiB Swap:  1904636 total,  1770500 free,   134136 used.   535356 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 5069 user      20   0  288332 190576   3112 R 100.0 20.2 217:39.61 counterparty-se
 8648 user      20   0    6712   2528   1988 R   5.5  0.3   0:00.08 top
 1162 snmp      20   0   11832   1052    720 S   1.8  0.1  44:45.59 snmpd
 4877 user      20   0  405504 169204   2640 S   1.8 18.0 134:27.62 bitcoind

```

**Comment by littleskunk** [comment]
My NAS should be faster than a Pi3. That can't be the reason. 

Maybe a problem with the bootstrap DB? Is it better to start with an empty DB?

**Comment by unsystemizer** [comment]
There's no difference, I've done the both and have several different setups. Currently I'm using Ubuntu 16.04 LTS for ARM (on Pi 2).

**Comment by littleskunk** [comment]
I was forced to stop it again.
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
138 root      20   0 2129296 1.124g      0 D   0.7 60.9  10:23.41 counterparty-se
```

**Comment by unsystemizer** [comment]
Mine runs within 300-400 MB and I don't have any special settings in server.conf: I have the usernames & passwords and locations of data and log files, that's all. 
My bitcoin.conf settings are all set down to the minimums. It's a Pi 2 with a SATA disk running Ubuntu 16.04 LTS.
![image](https://cloud.githubusercontent.com/assets/13134193/21604381/dc310c58-d1dd-11e6-9e63-b9871d2d67a1.png)

**Comment by unsystemizer** [comment]
I used to see this cache bloating issue before (https://github.com/CounterpartyXCP/counterparty-lib/issues/846) but not since 9.55. Before I used Raspbian, now Ubuntu 16.04 for ARM, so maybe something else changed.
What OS and version are you running?
You can try to `echo 3 > /proc/sys/vm/drop_caches` when it bloats like that, but when I had this problem I tried many different things and couldn't solve it.

**Comment by littleskunk** [comment]
Start bitcoind with a very high relay fee `-minrelaytxfee=0.2` and you will have a small mempool.
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 7799 root      20   0  729448 153188   7060 S   3.0  7.9  12:41.74 counterparty-se
11642 root      20   0 3375752 283064  15800 S   1.7 14.6   2:50.42 bitcoind
```

There is one disadvantage. Bitcoind will not broadcast new transactions. This is a bitcoind issue and they are working on it. My workaround at the moment is to change the value, restart bitcoind, generate and broadcast new transactions and finaly restart bitcoind with a very high relay fee again. Bitcoind will go on broadcasting the transactions.

Thank your for our help. That setup works for me and I will wait for the new bitcoind release. That will allow me to ignore bitcoind exceptions and broadcast it without two bitcoind restarts.
