### ISSUE TITLE
What replaces deprecated get_asset_info(assets) API method?

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/counterparty-lib#753]
Changelog for v9.51 mentions "Deprecate get_asset_info(assets) API method".
What replaces it?

@ivanaszuber official documentation still contains this deprecated method.
##

**Comment by ouziel-slama** [comment]
you can use `get_issuances()` and `get_supply()` to get all the informations returned by the old `get_asset_info()`.

**Comment by ivanaszuber** [comment]
Here's the proposed documentation update https://github.com/CounterpartyXCP/Documentation/pull/70

**Comment by adamkrellenstein** [comment]
Done

**Comment by jdogresorg** [comment]
Any chance we could get a single call that returns the same info as get_asset_info() without the need to make 3 separate calls to get_assets(), get_issuances(), and get_supply()?

**Comment by cryptonaut420** [comment]
I agree with J-dog we definitely should not have to make 3 seperate API calls just to get the same info as what was previously done in 1 command. idk about J-Dog but all I need is something that will give me the asset name, description, current supply and    divisibility. whats wrong with just having get_assets just like the rest of the get_{table} functions?

**Comment by adamkrellenstein** [comment]
@cryptonaut420: there is no `assets` table, actually---just `balances` and `issuances`. There could be, though.

**Comment by cryptonaut420** [comment]
@adamkrellenstein assets table would be handy, and also make it consistent with the rest of the data commands

**Comment by robby-dermody** [comment]
FYI, counterblock maintains such an assets table.

**Comment by cryptonaut420** [comment]
Running a whole other layer just to get a list of assets doesn't seem like a solution to me. Assets are one of the primary features, they should be able to be looked up easily with just native counterparty-lib

**Comment by robby-dermody** [comment]
@cryptonaut420 I agree. Just stating what was available in the meantime. I think we're open to have this feature, someone just has to get around to doing it.

**Comment by cryptonaut420** [comment]
fair enough, thanks!

**Comment by unsystemizer** [comment]
@robby-dermody since the method is already in `master`, what needs to be done in terms of development (except remove the deprecation warning)?

**Comment by deweller** [comment]
There is an assets table now.  But it doesn't maintain the latest issuance data (such as divisibility or the last description).

**Comment by robby-dermody** [comment]
Agreed that it would be nice to track asset state in an assets table. Counterblock does that and moving that logic to Counterparty-lib would be a bonus.
