### ISSUE TITLE
total asset holder balances exceed total asset issuance

### ISSUE THREAD

**Issue by loon3** [CounterpartyXCP/counterparty-lib#770]
Total asset holder balances of MOOLAH exceed total issuance by 0.00000002, possible float point rounding error...

https://counterpartychain.io/asset/MOOLAH
http://blockscan.com/assetInfo/MOOLAH#assetholders

**Comment by ivanaszuber** [comment]
`balances` shows the correct sum, but it seems block explorers are rounding the balances (999934705,99999998 rounded to 999934706)

**Comment by loon3** [comment]
Upon further investigation, this appears to be a block explorer issue and not a counterpartyd issue
