### ISSUE TITLE
Clean install, can I use Bitcoin Core 0.10 on Ubuntu?

### ISSUE THREAD

**Issue by snitko** [CounterpartyXCP/counterparty-lib#771]
I'm doing a clean install on Ubuntu 14.04

This documentation: http://counterpartydocumentation.readthedocs.org/en/latest/installation.html says Bitcoin Core 0.10 is not supported yet, however reading through these docs https://github.com/rippler/btc-jmcorgan-addrindex-v0.9.2.0-fca268c-beta it looks like it is recommended to install Bitcoin Core 0.10 instead of a patched 0.92.

Can you advise?

**Comment by btcdrak** [comment]
The recommended repo is now https://github.com/btcdrak/bitcoin/tree/addrindex released herehttps://github.com/btcdrak/bitcoin/releases/tag/addrindex-0.10.1

**Comment by rippler** [comment]
I briefly tested @btcdrak 's 0.10.1 build with Counterparty 9.51 on both Windows (`-lib`) and Linux (Federated Node on U 14.04) and didn't see any differences vs. the previous build (also built by BTCDrak) or issues.
