### ISSUE TITLE
Exception checking if coinbase TX is spendable (is_scriptpubkey_spendable)

### ISSUE THREAD

**Issue by arhuaco** [CounterpartyXCP/counterparty-lib#772]
The function is_scriptpubkey_spendable crashes with this TX. It's a coinbase TX.

01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0b01670101062f503253482fffffffff0100f2052a01000000232102082bdbf39bfd04621a1459ffb0f19b4b3afbc0f53d9c68495d520c1ba60b2e4eac00000000

This is the script:

"script_string":"02082bdbf39bfd04621a1459ffb0f19b4b3afbc0f53d9c68495d520c1ba60b2e4e OP_CHECKSIG"

You only need to check the hash for coinbase TXs.

My guess this one should be considered spendable. For now I'll just generate a new address and use that instead.

**Comment by arhuaco** [comment]
This could be a fix for this function. But then things crash elsewhere (while sorting by txid). I wonder if fixing that is too complex to support this kind of inputs.

 def get_checksig(asm):
+    pubkeyhash = None
     if len(asm) == 5 and asm[0] == 'OP_DUP' and asm[1] == 'OP_HASH160' and asm[3] == 'OP_EQUALVERIFY' and asm[4] == 'OP_CHECKSIG':
         pubkeyhash = asm[2]
-        if type(pubkeyhash) == bytes:
-            return pubkeyhash
+    elif len(asm) == 2 and asm[1] == 'OP_CHECKSIG':  # Coinbase transaction.
+        pubkeyhash = asm[0]
+    if type(pubkeyhash) == bytes:
+        return pubkeyhash

**Comment by ouziel-slama** [comment]
@arhuaco, just test the function and works well with the hex you provide:

```
>>> from counterpartylib.lib import backend
>>> backend.is_scriptpubkey_spendable('01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff0b01670101062f503253482fffffffff0100f2052a01000000232102082bdbf39bfd04621a1459ffb0f19b4b3afbc0f53d9c68495d520c1ba60b2e4eac00000000', '19w6vaUpAu4VBDd4VakCznhjLeNeaET1Ac')
False
>>>
```

What are you doing exactly to get the error, and what error ?

**Comment by arhuaco** [comment]
@ouziel-slama: You sent the whole transaction and not the script. Please try this:

    backend.is_scriptpubkey_spendable('2102082bdbf39bfd04621a1459ffb0f19b4b3afbc0f53d9c68495d520c1ba60b2e4eac', '19w6vaUpAu4VBDd4VakCznhjLeNeaET1Ac')

**Comment by ouziel-slama** [comment]
@arhuaco: fixed here https://github.com/CounterpartyXCP/counterparty-lib/commit/99876baddb346d4483ff2089407a4ae07f21746f (coinbase can not be use as input for Counterparty transaction)
