### ISSUE TITLE
Spurious Blockchain Reorganizations while Backend Catches Up

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#773]
On testnet:
```
[...]
[INFO] Block: 386149
current: 386150
current: 386149
[WARNING] Blockchain reorganisation at block 386149.
[INFO] Reparsing all transactions.
[INFO] First hash changed. Cleaning txlist_hash.
[INFO] Database minor version number updated.
current: 386149
[INFO] Block: 386149
current: 386150
[INFO] Block: 386150
current: 386151
[INFO] Block: 386151
[...]
```

**Comment by mtbitcoin** [comment]
I've noticed the same for TESTNET.  However, it looks like it has something to do with bitcoind as the blocks were coming in burts

**Comment by adamkrellenstein** [comment]
I only ever saw it on testnet myself.

**Comment by mtbitcoin** [comment]
I am not entirely sure this is counterpartyd related though, if you check the incoming blocks in bitcoind they were coming in every few seconds or so in the last incident. I also checked blockr testnet and it showed the same spurt of incoming blocks.

**Comment by adamkrellenstein** [comment]
Closing for now.
