### ISSUE TITLE
How do I start a counterparty-server as a daemon if I don't have sv command?

### ISSUE THREAD

**Issue by snitko** [CounterpartyXCP/counterparty-lib#775]
So, `runit` is not installed on my system and `sv` command is not available. Thus, I couldn't run `sudo sv start counterpartyd`. I installed `runit` but then trying to launch the counterparty server with `sv` didn't work, because it couldn't find that script. My guess it is because I installed counterparty BEFORE installing `sv`.

How do I run `counterparty-server` command as daemon manually?

**Comment by rippler** [comment]
1. It should be possible to use a command similar to this:
`sudo su -s /bin/bash -c 'counterparty-server --config-file /home/xcp/.config/counterparty/server.[testnet.]conf start' xcpd`
2. counterparty-server start command:
https://github.com/CounterpartyXCP/Documentation/blob/master/CLI/counterparty-cli.md

If questions aren't about bugs, perhaps you can post theme to the forums (https://counterpartytalk.org/c/support) for a faster response.
