### ISSUE TITLE
send command hangs and fails when mempool > 10,000

### ISSUE THREAD

**Issue by cryptonaut420** [CounterpartyXCP/counterparty-lib#784]
This is something we have noticed with the recent spam transaction DDoS attacks on the Bitcoin work. When the mempool on your bitcoind server has over 10,000 transactions (largest I tested with was around 35K), the create_send commands to counterparty hang. Something is either locking up or being incredibly slow to process. This may be related to the searchrawtransactions function in the addrindex bitcoind patch.

I tried making a send transaction and let it sit there... about an hour later it finally finished with the following error:

```
counterpartylib.lib.backend.addrindex.BackendRPCError: {'message': 'No information available about transaction', 'code': -5}
```

Restarting bitcoind appears to fix this temporarily, and also setting your mintxrelayfee setting to something like 0.00005 BTC causes your node to ignore most of these spam transactions, which seems to help. That being said, I would say this is high priority and a solution needs to be figured out soon because right now having a large mempool effectively kills your counterparty server. 

Could also be related to #783

**Comment by adamkrellenstein** [comment]
Definitely closely related to #783
