### ISSUE TITLE
testnet: apsw.ConstraintError: UNIQUE constraint failed: transactions.tx_hash

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#789]
counterparty-lib `develop` (from July 30, I believe), with Bitcoin Core 0.11 from btcdrak's source.

```
[INFO] Block: 526440 (4.04s)
[INFO] Block: 526441 (3.78s)
[INFO] Block: 526442 (3.78s)
[INFO] Block: 526443 (3.84s)
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/blocks.py", line 1074, in follow
    mempool_tx_index = list_tx(db, None, block_index, curr_time, tx_hash, mempool_tx_index)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/blocks.py", line 739, in list_tx
    data)
  File "src/cursor.c", line 231, in resetcursor
apsw.ConstraintError: ConstraintError: UNIQUE constraint failed: transactions.tx_hash

```

**Comment by arhuaco** [comment]
Hello. I've been seeing this issue as well. It seems restarting is the workaround.

**Comment by smoochytherhino** [comment]
Can confirm, I'm having the same issue here.

Please consider my the bounty, goes to whomever fixes this.
[![Synapsi bounty](https://synapsi.com/bb/65/12/bd/43/d9caa6e02c990b0a82652dca.png)](https://synapsi.com/questions/counterparty-lib-on-testnet:-apswconstrainterror:-unique-constraint-201509040003)

**Comment by adamkrellenstein** [comment]
@ouziel-slama can you try to fix this when you get the chance?

**Comment by ouziel-slama** [comment]
sure!

**Comment by ouziel-slama** [comment]
See this PR https://github.com/CounterpartyXCP/counterparty-lib/pull/792
The only explanation I found for this bug is that a already confirmed `tx_hash` appears in the mempool..

**Comment by adamkrellenstein** [comment]
@unsystemizer, @arhuaco, @smoochytherhino, please try with the latest commit to the `develop` branch, to verify that #792 fixed the problem.

**Comment by arhuaco** [comment]
Anecdotical evidence: I have been running an instance with #792 and counterparty-server hasn't crashed. Thanks for providing the PR.

**Comment by robby-dermody** [comment]
Closing. reopen if still an issue
