### ISSUE TITLE
Support Sending and Receiving Assets with P2SH (Multisig) Addresses

### ISSUE THREAD

**Issue by deweller** [CounterpartyXCP/counterparty-lib#791]
Treat P2SH addresses as first class citizens in Counterparty.  These addresses should be able to receive and send assets just like public key hashes.

Currently all addresses in a multisig transaction have to have a prior non-multisig transaction published on the blockchain in order for Counterparty to fetch their pubkey.  This limitation is significant for certain applications.  Adding support for P2SH addresses would remove this constraint.

Adding support for P2SH addresses would also reduce transaction size for users wishing to send funds to multisig addresses.

**Comment by rubensayshi** [comment]
closing, P2SH support was merged in develop
