### ISSUE TITLE
exectracer is fragile

### ISSUE THREAD

**Issue by robby-dermody** [CounterpartyXCP/counterparty-lib#795]
e.g. https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/database.py#L38

couldn't I technically then include an asset or something with "blocks" or "transactions" in the description, and cause the exectracer to be skipped.... ?

all in all, the 'in' approach to analysis is just begging for trouble... :/

**Comment by adamkrellenstein** [comment]
Sure, that should be `if category == 'blocks' [...]`, I think?!

Let's include the fix for this in v9.51.4.

**Comment by adamkrellenstein** [comment]
See #796

**Comment by robby-dermody** [comment]
In thinking that splitting on " or ' and taking the first part of the string may be enough, as you get all Sql before any string in the statement begins... Thoughts?

**Comment by ouziel-slama** [comment]
hum.. I think is simpler to just use the variable `category`.. I refactor this few lines here: https://github.com/CounterpartyXCP/counterparty-lib/pull/797
