### ISSUE TITLE
Changelogs title "Client versions"?

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#805]
Here (also counterblock) the title in CHANGELOG.md is "Client Versions".
I don't know if that's correct (what should be the title in Counterparty CLI's Changelog?), but it's certainly confusing.

**Comment by robby-dermody** [comment]
See https://github.com/CounterpartyXCP/counterparty-lib/commit/9c0e6e11af82af859c13af8bb621587075aa1b14
