### ISSUE TITLE
Require requests >=2.8.1

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#808]
I've seen several bugs with `requests` v2.5.1 just today on an up-to-date Ubuntu 14.04.
I don't seem to remember seeing those before. 
Upgrade to 2.8.1 helps. 
Can we up the minimum requirement to v2.8.1?

**Comment by robby-dermody** [comment]
This is already the case. The newest version of `requests` should always be used:

https://github.com/CounterpartyXCP/counterparty-lib/blob/master/setup.py#L167

**Comment by unsystemizer** [comment]
Okay, but what about https://github.com/CounterpartyXCP/counterparty-lib/blob/master/requirements.txt#L3
