### ISSUE TITLE
Uncaught exception in testnet ('invalid pushdata due to truncation').

### ISSUE THREAD

**Issue by arhuaco** [CounterpartyXCP/counterparty-lib#810]
Hello. When I try to run:

    counterparty-client send --source mogTjt1DU1trpKsXgoesEL1J2PkXmyStnE  --destination mognqybiU68RwJExYscAaBhf9gkpVc1UAV  --quantity 1 --asset SPTEST

I get the following exception:

    counterpartycli.util.RPCError: {'data': {'type': 'DecodeError', 'message': 'invalid pushdata due to truncation', 'args': ['invalid pushdata due to truncation']}, 'code': -32000, 'message': 'Server error'}

I debugged a bit and found out that the exception happens when counterpartylib/lib/script.py:get_asm is processing TX [720b1a0a17cf19718a8bdfc65b0f2d3558e3e13e210c3c8da14496f9c05d00d9](http://testnet.blockscan.com/txInfo/3986).

What could be the issue?

Running counterparty-lib v9.52.0 and counterparty-cli v1.1.1 without modifications.

**Comment by arhuaco** [comment]
Hi there. I still cannot log in into https://testnet.counterwallet.io/ because of this issue :-/

**Comment by robby-dermody** [comment]
that transaction shows up on blockscan as a send (http://testnet.blockscan.com/txInfo/3986).

But it has an extra odd output: https://test-insight.bitpay.com/tx/720b1a0a17cf19718a8bdfc65b0f2d3558e3e13e210c3c8da14496f9c05d00d9 shows a 4th output with the following scriptPubkey: ```OP_RETURN OP_3 OP_VERIF OP_DEPTH OP_VERNOTIF OP_VERIFY OP_DUP OP_VERIF 7361797320686921```

Another send transaction on testnet (that processes fine) is https://test-insight.bitpay.com/tx/3eb26ebae2424d865dd726803c5d35e5a3ab382dbb37882e020899b3e816a78c (http://testnet.blockscan.com/txInfo/4384). That doesn't have that same output (only has 3 outputs)

Looking at it further, it looks like someone threw together a custom message with an extra OP_RETURN output: https://www.blocktrail.com/tBTC/tx/720b1a0a17cf19718a8bdfc65b0f2d3558e3e13e210c3c8da14496f9c05d00d9#tx_messages

The OP_RETURN decodes down to "Setfive says hi!"

@adamkrellenstein @rubensayshi could possibly enhance the transaction parsing code to ignore extra outputs like these (at least with something with a set size, like simple send operations). That, or not allowing encoding strategies to be mixed (go with the first e.g. multisig in this case, ignore any outputs with the second). I'd personally have to look further into our standard transaction parsing code, but don't have the time ATM.

**Comment by arhuaco** [comment]
Hi there! I did this OP_RETURN thing :-/ Sorry, I was testing something.
In any case, this opens a path for a D.O.S. attack where people send other assets in a similar way and then people won't be able to open counterwallet nor to use their Counterparty servers.
It's easy to do this, so this should probably be a security issue.

**Comment by rubensayshi** [comment]
hmm I think making `get_tx_info` more strict and not allowing mixing of encoding is a good idea in general.

but I don't understand how this exception is being thrown, once the `change` is found it has a `break` and shouldn't try to get the asm for the op_return with the message anyway, I can't reproduce it!

**Comment by adamkrellenstein** [comment]
> not allowing mixing of encoding is a good idea in general

:+1: the existing protocol is too flexible
