### ISSUE TITLE
Remove plaintext pass from " Could not connect to backend at "

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#835]
When CP loses connection to blockchain back-end it logs that like so:

```
2016-03-02-T16:51:01+0000 [DEBUG] Could not connect to backend at `http://rpc:1234@192.168.0.2:8332`. (Try 1/12)
```

`1234`, or even the entire part between `//` and `@`, should be cut out or replaced with `X` or hashes or something like that. While it's valuable to know what username/pass were used to access, it's not a good idea to have plaintext auth details in the log.

The message appears in code for both Bitcoin Core and btcd:
- https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/backend/addrindex.py#L37
- https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/backend/btcd.py#L37
##

**Comment by mtbitcoin** [comment]
I am running in similar issues...

**Comment by unsystemizer** [comment]
Maybe this improvement (https://github.com/CounterpartyXCP/federatednode_build/issues/274, if we implement cookie-based auth) will mask or solve this issue.
