### ISSUE TITLE
User newer Sqlite?

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#871]
In setup.py we download and build sqlite-amalgamation 3.8.7.3-r1

Quite a lot of (performance and other) improvements and bug fixes happened in Sqlite since 3.8 (now 3.13, Ubuntu 16.04 ships with 3.11). 

Could we consider using a newer version? 
What kind of "CP DB stress test" would be appropriate?

**Comment by unsystemizer** [comment]
I've been using 3.12.2 for days, no apparent issues.

**Comment by rubensayshi** [comment]
closing, pending https://github.com/CounterpartyXCP/counterparty-lib/issues/890 merge
