### ISSUE TITLE
Replace Pure-Python Row Tracer

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#892]
There may be very significant performance losses from using this pure-Python row tracer: https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/database.py#L15-L20

The alternative would be just `db.row_factory = sqlite3.Row`, with the `sqlite3` library in place of `apsw`. That would have no impact or performance.
##

**Comment by rubensayshi** [comment]
you recall what the reason is for using apsw?  
is it for the `.backup()`?

**Comment by adamkrellenstein** [comment]
There was no particular reason in the beginning. It might be necessary for some of the nested transactions, though?

**Comment by robby-dermody** [comment]
Seems like it was due to `apsw` being thread safe. We could use `sqlite3` if we were careful about using a separate connection per thread... (For instance, `flask` currently creates a separate thread per API request, we can utilize a before_request hook to set up a connection there, which may not be that performant, or utilize a process model with it instead). 

I don't know about `backup()` though...

**Comment by rubensayshi** [comment]
`backup` can be replaced with just dumping/loading SQL statements, atm we `backup()` copy the whole DB and then drop almost all tables except blocks, we could just only dump/load what we need, should be as fast or faster.

`apsw` has `with` context manager to do SAVEPOINT based transactions, while `sqlite3` just uses `COMMIT`/`ROLLBACK`, we'd have to make a custom context manager for the places where we need `SAVEPOINT` (I'm using it in the EVM stuff at least).

I think `apsw` by default autocommits everything, `sqlite` has a bunch of modes and by default only autocommits if you do a `SELECT` after `INSERT/UPDATE` statements, but `db.isolation_level = "IMMEDIATE"` is an easy fix for that.

We use the `apsw.setexectrace` to update the `BLOCK_MESSAGES` and `messages` table, I don't see a way to do that with `sqlite3`, but it should be possible I think...

**Comment by adamkrellenstein** [comment]
Going to re-evaluate all of this as part of #1312
