### ISSUE TITLE
Use of custom_inputs in create_send causes error

### ISSUE THREAD

**Issue by poloniex** [CounterpartyXCP/counterparty-lib#923]
If custom_inputs is set when calling create_send, the operation fails with the error "local variable 'unspent' referenced before assignment." The problem appears to be here: https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/transaction.py#L531

Commenting the logger.debug line out restores functionality, but a better solution may be to add a check for custom_inputs is None to the conditions in this if statement: https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/transaction.py#L522
##

**Comment by robby-dermody** [comment]
Thanks Tristan. Will get this fixed as a hotfix to master here shortly.
