### ISSUE TITLE
Error python setup.py

### ISSUE THREAD

**Issue by longpq18** [CounterpartyXCP/counterparty-lib#930]
Hello,
I have install counterparty-lib using for bitcoin and it's issue with python, i using ubuntu 14.04
This is error in terminal : 
   "  Command "python setup.py egg_info" failed with error code 1 in /home/hklog/counterparty-cli "
How doing fix it ?
Thanks so much.
##

**Comment by unsystemizer** [comment]
* You posted this bug to https://github.com/unsystemizer/counterparty-config-example/issues/1#issuecomment-248797146 and I asked you what command you executed to get there. Please close that (or this) issue and provide steps that cause the problem.
* The install procedure from https://github.com/CounterpartyXCP/counterparty-lib/blob/master/README.md works fine on both up-to-date Ubuntu 14.04 and 16.04. A complete log of installation on Ubuntu 14.04 can be found at http://pastebin.com/ztj0Me6H.

**Comment by adamkrellenstein** [comment]
Fixed
