### ISSUE TITLE
Improve the insufficient balance message

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#935]
https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/messages/issuance.py#L144 just says insufficient balance. 
Many people look at BTC only and ignore the fact that XCP may also be required for issuance. 

Another issue is with `issuance`: if asset `description` is over the limit, you still get the insufficient BTC balance message.  I need to verify this and for this I'd create a separate issue later.

**Comment by unsystemizer** [comment]
Just came across this again when using Counterwallet. 

* There's 0.04 BTC at the address, but it can't send 0.03 BTC. 
* Counterwallet is telling me I need 0.00174815 BTC more than I have (0.04513254 (supposed requirement) - 0.04338439 (balance)).
* I used https://www.biteasy.com/developers/sandbox#!/unspent-outputs/get_unspent_outputs_get_0 to check the number of unspent outputs - the address has > 100 of them. 

Are there too many unspent outputs? I tried the redeem site, it also can't deal with the address. 
What else can I try to debug this?

**Comment by unsystemizer** [comment]
Recording further progress:

* Tried with Joe's browser-based wallet, hit an error whereby the minimum tx fee necessary was 8K sats, and the wallet hard-codes it at 2K. At least I got an error. 
* Same as in my 
* Related to the `MAX` button in CW, it seems to work very simplistically - (balance-0.0002) - so I'll open another issue in CW

Next I'll try to debug from within Bitcoin Core.

**Comment by unsystemizer** [comment]
I was able to solve this in RarePepeWallet by checking bitcore debug which said 8000 satoshi was required, which I then set that in my wallet settings and was able to send from it.

**Comment by unsystemizer** [comment]
Example: address with 0.16 BTC can't transfer asset to another, because it doesn't have at least 0.0007 BTC.
Sends, issuance, transfers, everything is impacted and even if you transfer $160 (0.16 BTC on mainnet) you still can't do much with in the wallet. 

![image](https://cloud.githubusercontent.com/assets/13134193/21686889/fd4ed68e-d3a1-11e6-9608-097c5065e45d.png)

**Comment by adamkrellenstein** [comment]
This doesn't sound like a bug in `counterparty-lib`.
