### ISSUE TITLE
Table "destructions" is empty

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#937]
https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/util.py#L470 says `destructions` ought to contain something, but the table is completely empty.

Query:
`SELECT SUM(quantity) AS total FROM destructions WHERE (status='valid' AND asset='XCP')`

**Comment by unsystemizer** [comment]
On a second thought, it's probably supposed to be empty, but if that's the case why is the code in there?

**Comment by rubensayshi** [comment]
there's a `destroy` message to destroy assets: https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/messages/destroy.py

just never used

**Comment by unsystemizer** [comment]
LOL, Okay I will destroy something just to be the first one. 
I did try to use `destroy` in the CLI but it doesn't work (I opened a bug for that in `-cli`). 
Closing this one.
