### ISSUE TITLE
Incorrect warning about the DB being 4 hours behind Bitcoin Core

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#938]
I ran into this today on one mainnet instance, it reported to be 4 hours behind although they were in sync (same block height) and not behind blockchain.info.
I think this is the problematic area:
https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/api.py#L91

**Comment by rubensayshi** [comment]
any idea which blocks those were? and is it gone now?

**Comment by unsystemizer** [comment]
Damn, it didn't occur to me I should record the height. 
I checked the 2 servers' logs but didn't find any occurrences of `ehind` in them. I think I may have obtained that with `counterparty-client getinfo`, but there are no logs for the client so I can't tell for sure. I'll get more detailed info if it happens next time.

**Comment by jdogresorg** [comment]
closing issue. Please reopen if this is still a problem.
