### ISSUE TITLE
SerializationTruncationError with addrindex 0.13.2 on testnet

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#950]
Got this twice after restarting a formerly (when Core was addrindex 0.12.1) valid CP DB following an in-place upgrade from addrindex 0.12.1 to 0.13.2 beta. This appears right away and counterparty-server stops. I "solved" this by recreating the DB from scratch using `reparse`. 

* v9.55.1
* addrindex 0.13.2 beta
* Ubuntu 16

```
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.1-py3.5.egg/counterpartylib/server.py", line 408, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.1-py3.5.egg/counterpartylib/lib/blocks.py", line 1106, in follow
    current_cblock = backend.getblock(current_hash)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.1-py3.5.egg/counterpartylib/lib/backend/__init__.py", line 49, in getblock
    return CBlock.deserialize(util.unhexlify(block_hex))
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/serialize.py", line 115, in deserialize
    r = cls.stream_deserialize(fd)
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/__init__.py", line 506, in stream_deserialize
    vtx = VectorSerializer.stream_deserialize(CTransaction, f)
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/serialize.py", line 250, in stream_deserialize
    r.append(inner_cls.stream_deserialize(f))
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/__init__.py", line 329, in stream_deserialize
    vin = VectorSerializer.stream_deserialize(CTxIn, f)
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/serialize.py", line 250, in stream_deserialize
    r.append(inner_cls.stream_deserialize(f))
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/__init__.py", line 199, in stream_deserialize
    scriptSig = script.CScript(BytesSerializer.stream_deserialize(f))
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/serialize.py", line 234, in stream_deserialize
    return ser_read(f, l)
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/serialize.py", line 81, in ser_read
    raise SerializationTruncationError('Asked to read %i bytes, but only got %i' % (n, len(r)))
bitcoin.core.serialize.SerializationTruncationError: Asked to read 21246 bytes, but only got 561

```

**Comment by unsystemizer** [comment]
I tried to understand what's wrong but I can't. I have one instance with Core 0.12.1 and that is working fine (I also restarted it successfully). 

Another, which had this problem, had pycoin 0.70 (maybe that's what it was, I changed to 0.62 and now it can start without error (maybe it'll hit it later). 

Here's an example of the same error but with a much larger value, hitting [MAX_SIZE](https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/core/serialize.py#L34).
```
bitcoin.core.serialize.SerializationError: Asked to read 0x9580ccc02ffff bytes; MAX_SIZE exceeded
```
I checked the working (core 0.12.1) and non-working (core 0.13.2 beta) system, the both have `python-bitcoinlib (0.5.1)`

**Comment by unsystemizer** [comment]
Iit turns Bitcoin Core can seem okay and run without any errors, but still be corrupt... hope it's not just the addrindex branch. Reindexing now, will close this issue if that fixes the problem.

**Comment by unsystemizer** [comment]
After additional testing (one more clean start with a completely new blockchain and counterparty.testnet.db) my conclusion is:
* I have no issues with Bitcoin Core 0.12.1 addrindex + counterparty-lib 9.55.1 + testnet
* The exact same combination does **not** work (I get this serialization error) with Bitcoin Core 0.13.2 addrindex

**Comment by unsystemizer** [comment]
I get the same serialization error on Windows 10 (64-bit) with Python 3.5 32-bit.

**Comment by unsystemizer** [comment]
Could be [this](https://github.com/petertodd/python-bitcoinlib/pull/112)

**Comment by smno1** [comment]
I got the same issue: bitcoin.core.serialize.SerializationError: Asked to read 0x953437e02ffffff bytes; MAX_SIZE exceeded.  
By looking into the code, it seems that there is a check on MAX_SIZE.  I'd like to take your advice to try on 0.12. Hope it works 
`def ser_read(f, n):
    """Read from a stream safely

    Raises SerializationError and SerializationTruncationError appropriately.
    Use this instead of f.read() in your classes stream_(de)serialization()
    functions.
    """
    if n > MAX_SIZE:
        raise SerializationError('Asked to read 0x%x bytes; MAX_SIZE exceeded')
    r = f.read(n)
    if len(r) < n:
        raise SerializationTruncationError('Asked to read %i bytes, but only got %i' % (n, len(r)))
    return r`

**Comment by smno1** [comment]
I got the same issue: bitcoin.core.serialize.SerializationError: Asked to read 0x953437e02ffffff bytes; MAX_SIZE exceeded.
By looking into the code, it seems that there is a check on MAX_SIZE. I'd like to take your advice to try on 0.12. Hope it works

```
`def ser_read(f, n):
"""Read from a stream safely
Raises SerializationError and SerializationTruncationError appropriately.
Use this instead of f.read() in your classes stream_(de)serialization()
functions.
"""
if n > MAX_SIZE:
    raise SerializationError('Asked to read 0x%x bytes; MAX_SIZE exceeded')
r = f.read(n)
if len(r) < n:
    raise SerializationTruncationError('Asked to read %i bytes, but only got %i' % (n, len(r)))
return r`
```

**Comment by unsystemizer** [comment]
With 0.12 on it's worked flawlessly for us, never had this problem. This problem appears because of SegWit (which is enabled on Testnet) has larger block sizes. 
If you look at the thread at the link from my last comment above, a patch is out but [doesn't work yet](https://github.com/petertodd/python-bitcoinlib/pull/112#issuecomment-272716180) but after some minor modifications maybe it will.

**Comment by smno1** [comment]
Thank for your reply. Yes, I have seen the PR#112 and since you mentioned that it doesn't work in this branch thus I didn't try it. Currently I switch to 0.12 but it requires to rebuild and reindex the block which is quite time-consuming (2-3 days).  It would be really great if there is a way to speed up the process.

**Comment by unsystemizer** [comment]
Yes, you're right.
Because of reindex, I made a copy of testnet blockchain, so I have a copy for each version and can run either of them until this is solved (for now I'm running 0.12.1). Let's watch that issue and I'll try any promising patches as they come out.

**Comment by smno1** [comment]
Thanks for your advise. Already backed up 0.13 blockchain. Look forward your good news.

**Comment by robby-dermody** [comment]
Hi guys, the most recent counterparty-lib `develop` branch commit seems to reparse testnet fine now. what you'd need to do (on a fednode install, assuming you are using `develop` and not `master`):
```
fednode rebuild counterparty-testnet
fednode reparse counterparty-testnet
```

**Comment by y-zono** [comment]
I got the same (or similar) issue. 

* bitcoin addrindex 0.13.2
* counterparty-lib v9.55.2
* on testnet (mainnet is ok)

```
$ sudo /usr/bin/python3 /usr/local/bin/counterparty-server --config-file=/xxx/server.conf --database-file=/xxx/counterparty.testnet.db start

[2017-05-09 12:53:15][INFO] Running v1.1.2 of counterparty-server.
[2017-05-09 12:53:15][INFO] Running v9.55.2 of counterparty-lib.
[2017-05-09 12:53:15][INFO] Acquiring lock.
[2017-05-09 12:53:15][INFO] Connecting to database.
[2017-05-09 12:53:23][INFO] Connecting to backend.
[2017-05-09 12:53:23][INFO] Starting API Server.
[2017-05-09 12:53:33][INFO] Resuming parsing.
[2017-05-09 12:53:33][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.2', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/server.py", line 155, in main
    server.start_all(db)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.2-py3.5.egg/counterpartylib/server.py", line 408, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.2-py3.5.egg/counterpartylib/lib/blocks.py", line 1134, in follow
    current_cblock = backend.getblock(current_hash)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.2-py3.5.egg/counterpartylib/lib/backend/__init__.py", line 49, in getblock
    return CBlock.deserialize(util.unhexlify(block_hex))
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/serialize.py", line 120, in deserialize
    r, padding)
bitcoin.core.serialize.DeserializationExtraDataError: Not all bytes consumed during deserialization
```

I tried the followings but it didn't work.

```
// Replace DB
$ wget https://s3.amazonaws.com/counterparty-bootstrap/counterparty-db-testnet.latest.tar.gz

// Reparse
$ sudo /usr/bin/python3 /usr/local/bin/counterparty-server --config-file=/xxx/server.conf --database-file=/xxx/counterparty.testnet.db reparse
[2017-05-09 12:40:09][INFO] Database version number updated.
[2017-05-09 12:40:09][INFO] Reparse took 4.586 minutes.
[2017-05-09 12:40:09][INFO] Starting database VACUUM. This may take awhile...
[2017-05-09 12:40:38][INFO] Database VACUUM completed.
```

I don't use fednode. Do you have any ideas how to fix it ?

**Comment by robby-dermody** [comment]
make sure your python-bitcoinlib is updated to this specific version:
https://github.com/CounterpartyXCP/counterparty-lib/blob/master/docker/start.sh#L15

fednode takes care of all of that for you

**Comment by smno1** [comment]
It probably due to that testnet already activated segwit and cause some block larger than 1m. (Segwit is introduced in bitcoin core in 0.13 and activated in testnet). You can try @robby-dermody solution.

**Comment by y-zono** [comment]
Thank you. It worked.

This is what I did:

```
$ sudo rm -rf /usr/local/lib/python3.5/dist-packages/bitcoin /usr/local/lib/python3.5/dist-packages/python_bitcoinlib-*.dist-info
$ sudo pip3 install --upgrade git+https://github.com/CounterpartyXCP/python-bitcoinlib.git@112d66b11cde30b9c7e10895f057baab13cc35ec#egg=python-bitcoinlib-0.7.0
```

I didn't know how fednode worked. I will look into it.

**Comment by herrmoltke** [comment]
FYI I just bumped my `python-bitcoinlib` to `v0.9.0` and `counterparty-server` has successfully resumed parsing. I don't know however whether there are any secondary, negative consequences of doing this, so I don't want to make a PR with this change. You can feel free to close this, though.

**Comment by chiguireitor** [comment]
Solved with latest python-bitcoinlib
