### ISSUE TITLE
Choose pubkeyhash encoding if asset description length >41 bytes and < 53 bytes?

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#955]
I created the [same issue](https://github.com/CounterpartyXCP/counterwallet/issues/810) in Counterwallet so in a way this is a duplicate, but arguably it could be done in the both places, because there's also counterparty-client which also doesn't set its encoding appropriately, so unless there's another way, either the client or the server need to pick `pubkeyhash` when appropriate or else throw a meaningful error.

As far as the client is concerned, I documented this (use `encoding: pubkeyhash` when description > 41 and under 52 bytes) in the CLI docs, but it's not in online help, and if we don't touch counterparty-lib then the client needs to be able to pick the right encoding by itself or at least have this information in online help. So I suggest we leave this open until we decide where it has to be fixed (here in in counterparty-client).

Related: this is one of seemingly several different cases where incorrect "insufficient balance" error appears. I created a separate issue for that here: https://github.com/CounterpartyXCP/counterparty-lib/issues/935 and I'll leave that open until we stop seeing unidentified reasons for that error message.

**Comment by robby-dermody** [comment]
@rubensayshi are you in favor of forcing P2PKH encoding in this case for now, before we get P2SH encoding finalized , or would you rather just push forward with your P2SH scheme on he network as-is (ie without segwit)?

**Comment by deweller** [comment]
Closed with https://github.com/CounterpartyXCP/counterparty-lib/pull/1005
