### ISSUE TITLE
Error:API Exception

### ISSUE THREAD

**Issue by liqingchao** [CounterpartyXCP/counterparty-lib#960]
to many bugs;

when send: 
Error:API Exception: {'args': ("unsupported operand type(s) fro -: 'set' and 'KeysView'",)....

WHY...

**Comment by unsystemizer** [comment]
What was your API call?
Most likely the request was not correctly formed.

**Comment by liqingchao** [comment]
here is the logs: 
![image](https://cloud.githubusercontent.com/assets/3369861/22772527/1bf2911a-eed8-11e6-9784-641e5a34fef3.png)

**Comment by unsystemizer** [comment]
Okay so that was a CLI or API call which is wrong. 
You didn't use the correct command. 
What was the command or API call you tried?

**Comment by robby-dermody** [comment]
This error is due to you using python3.3. counterparty-lib requires python3.5+
