### ISSUE TITLE
Insufficient BTC Error after replacing from encoding=multisig to encoding=pubkeyhash for -bytespersigop.

### ISSUE THREAD

**Issue by y-zono** [CounterpartyXCP/counterparty-lib#962]
When I issue a new token, I got "Insufficient BTC" error even thought the address has sufficient BTC. I'm using v9.55.1 counterparty-lib and it happens on coindaddy.io as well like below.

```
$ curl -X POST https://public.coindaddy.io:4001/api/ --user rpc:1234 -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript' --data-binary '{"jsonrpc":"2.0", "id":0, "method":"create_issuance", "params":{"source":"17sdLuNtD7ZpFCVZ3Doz58fwxFF6i6CKk2", "quantity":1, "asset":"A1382723823927482474", "divisible":true, "description":"xxx.sampledomain.com/token/A1382723823927482474.json"}}'

{"error": {"message": "Error composing issuance transaction via API: Insufficient BTC at address 17sdLuNtD7ZpFCVZ3Doz58fwxFF6i6CKk2. (Need approximately 0.00156043 BTC.) To spend unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi\u2010sig addresses.)", "code": -32001}, "id": 0, "jsonrpc": "2.0"}
```

The address's utxo. It has sufficient balance and matched the bytespersigop condition.

```
[
   {
      'amount':0.00629541,
      'confirmations':1654,
      'vout':1,
      'txid':'45eff5aac1810f8fd4325cd632b9382120277d2875bc1b537408535a340c6d4b',
      'scriptPubKey':'76a9144b63e3f9d862f4eaeca868997b9a27dcb10e3e2688ac'
   },
   {
      'amount':8.069e-05,
      'confirmations':9124,
      'vout':2,
      'txid':'87b07807eba94e75569d9e6a0a3582299826900f6cded304f886411817fd7edf',
      'scriptPubKey':'76a9144b63e3f9d862f4eaeca868997b9a27dcb10e3e2688ac'
   }
]
```

I think UTXO_LOCKS is not initialized after replacing from encoding=multisig to encoding=pubkeyhash for -bytespersigop.

https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/transaction.py#L549

It worked after I added the following code. 

```
if encoding == 'multisig' and inputs and data_output and len(inputs) < len(data_array) * 2 and util.enabled('bytespersigop'):
    if UTXO_LOCKS is not None and config.UTXO_LOCKS_MAX_ADDRESSES > 0:
        UTXO_LOCKS = util.DictCache(size=config.UTXO_LOCKS_MAX_ADDRESSES)
```

**Comment by robby-dermody** [comment]
you put that code at line 549? That is odd, if so, given that it's already in that function higher up: https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/transaction.py#L349

**Comment by deweller** [comment]
I'm also experiencing this in counterwallet when issuing an asset with a 50 character description.

**Comment by unsystemizer** [comment]
@deweller few weeks ago I made a change in the docs (here: 
https://github.com/CounterpartyXCP/Documentation/commit/dd1ab748e6d63937cefb44ab5a558787d9e769e6#diff-24b446263fae86834f9cba014b217a37R154, and also in the API docs) to make a note of that.
Over 41 bytes requires encoding to be set to pubkeyhash as far as I can tell.

**Comment by deweller** [comment]
Closed with https://github.com/CounterpartyXCP/counterparty-lib/pull/1005
