### ISSUE TITLE
get_asset_info and inefficient util.asset_supply method

### ISSUE THREAD

**Issue by deweller** [CounterpartyXCP/counterparty-lib#968]
get_asset_info calls `util.asset_supply`.  `util.asset_supply` lists every creation and destruction in the database and then sums those pertaining to the given asset.  

There are currently over 80k issuances in the database which makes this method slow and memory intensive.

Instead we should allow the `creations` and `destructions` functions to accept an optional `asset` argument.  Then these methods can pull only the rows from the database pertaining to the asset we are interested in.  This should significantly speed up this method and reduce memory usage.

As a side note, I think `get_asset_info` is a useful API feature and should not be removed.  (It is currently marked as deprecated - probably for this reason.)

Related: #753

**Comment by jdogresorg** [comment]
the issue with `util.asset_supply` has been fixed in 2934216b90114a74a97dab8516469d13b4e80f3b to specify the asset as suggested here.

Also, I have updated the docs to remove the note about `get_asset_info` being depreciated... it is a helpful API feature which I have no plans to depreciate.
