### ISSUE TITLE
[Bitcoin 0.15] accommodate changes to fee estimate RPCs

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#997]
Details on what's changed:
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.15.0.md#changes-to-fee-estimate-rpcs

**Comment by droplister** [comment]
I submitted a PR which I think accomplishes this change. My code does not let you choose between estimatefee or estimatesmartfee, but I think that's okay because estimatefee is deprecated.
